// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logger.proto

package dmp_tracking;

public final class Logger {
  private Logger() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface common_logOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 request_time = 1;
    /**
     * <code>required int64 request_time = 1;</code>
     *
     * <pre>
     *unixtime 
     * </pre>
     */
    boolean hasRequestTime();
    /**
     * <code>required int64 request_time = 1;</code>
     *
     * <pre>
     *unixtime 
     * </pre>
     */
    long getRequestTime();

    // required uint32 ip = 2;
    /**
     * <code>required uint32 ip = 2;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    boolean hasIp();
    /**
     * <code>required uint32 ip = 2;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    int getIp();

    // required int32 status = 3;
    /**
     * <code>required int32 status = 3;</code>
     *
     * <pre>
     * http status 
     * </pre>
     */
    boolean hasStatus();
    /**
     * <code>required int32 status = 3;</code>
     *
     * <pre>
     * http status 
     * </pre>
     */
    int getStatus();

    // required string uri = 4;
    /**
     * <code>required string uri = 4;</code>
     *
     * <pre>
     * http request line not include param 
     * </pre>
     */
    boolean hasUri();
    /**
     * <code>required string uri = 4;</code>
     *
     * <pre>
     * http request line not include param 
     * </pre>
     */
    String getUri();
    /**
     * <code>required string uri = 4;</code>
     *
     * <pre>
     * http request line not include param 
     * </pre>
     */
    com.google.protobuf.ByteString
        getUriBytes();

    // required string uid = 5;
    /**
     * <code>required string uid = 5;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    boolean hasUid();
    /**
     * <code>required string uid = 5;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    String getUid();
    /**
     * <code>required string uid = 5;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    // required string param = 6;
    /**
     * <code>required string param = 6;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    boolean hasParam();
    /**
     * <code>required string param = 6;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    String getParam();
    /**
     * <code>required string param = 6;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    com.google.protobuf.ByteString
        getParamBytes();

    // required string body = 7;
    /**
     * <code>required string body = 7;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    boolean hasBody();
    /**
     * <code>required string body = 7;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    String getBody();
    /**
     * <code>required string body = 7;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    com.google.protobuf.ByteString
        getBodyBytes();

    // required string ua = 8;
    /**
     * <code>required string ua = 8;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    boolean hasUa();
    /**
     * <code>required string ua = 8;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    String getUa();
    /**
     * <code>required string ua = 8;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    com.google.protobuf.ByteString
        getUaBytes();

    // required int64 process_time = 9;
    /**
     * <code>required int64 process_time = 9;</code>
     *
     * <pre>
     * </pre>
     */
    boolean hasProcessTime();
    /**
     * <code>required int64 process_time = 9;</code>
     *
     * <pre>
     * </pre>
     */
    long getProcessTime();

    // required string refer = 10;
    /**
     * <code>required string refer = 10;</code>
     *
     * <pre>
     * </pre>
     */
    boolean hasRefer();
    /**
     * <code>required string refer = 10;</code>
     *
     * <pre>
     * </pre>
     */
    String getRefer();
    /**
     * <code>required string refer = 10;</code>
     *
     * <pre>
     * </pre>
     */
    com.google.protobuf.ByteString
        getReferBytes();
  }
  /**
   * Protobuf type {@code dmp_tracking.common_log}
   */
  public static final class common_log extends
      com.google.protobuf.GeneratedMessage
      implements common_logOrBuilder {
    // Use common_log.newBuilder() to construct.
    private common_log(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private common_log(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final common_log defaultInstance;
    public static common_log getDefaultInstance() {
      return defaultInstance;
    }

    public common_log getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private common_log(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              requestTime_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ip_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              status_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              uri_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              uid_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              param_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              body_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              ua_ = input.readBytes();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              processTime_ = input.readInt64();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              refer_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Logger.internal_static_dmp_tracking_common_log_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Logger.internal_static_dmp_tracking_common_log_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              common_log.class, Builder.class);
    }

    public static com.google.protobuf.Parser<common_log> PARSER =
        new com.google.protobuf.AbstractParser<common_log>() {
      public common_log parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new common_log(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<common_log> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 request_time = 1;
    public static final int REQUEST_TIME_FIELD_NUMBER = 1;
    private long requestTime_;
    /**
     * <code>required int64 request_time = 1;</code>
     *
     * <pre>
     *unixtime 
     * </pre>
     */
    public boolean hasRequestTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 request_time = 1;</code>
     *
     * <pre>
     *unixtime 
     * </pre>
     */
    public long getRequestTime() {
      return requestTime_;
    }

    // required uint32 ip = 2;
    public static final int IP_FIELD_NUMBER = 2;
    private int ip_;
    /**
     * <code>required uint32 ip = 2;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 ip = 2;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    public int getIp() {
      return ip_;
    }

    // required int32 status = 3;
    public static final int STATUS_FIELD_NUMBER = 3;
    private int status_;
    /**
     * <code>required int32 status = 3;</code>
     *
     * <pre>
     * http status 
     * </pre>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 status = 3;</code>
     *
     * <pre>
     * http status 
     * </pre>
     */
    public int getStatus() {
      return status_;
    }

    // required string uri = 4;
    public static final int URI_FIELD_NUMBER = 4;
    private Object uri_;
    /**
     * <code>required string uri = 4;</code>
     *
     * <pre>
     * http request line not include param 
     * </pre>
     */
    public boolean hasUri() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string uri = 4;</code>
     *
     * <pre>
     * http request line not include param 
     * </pre>
     */
    public String getUri() {
      Object ref = uri_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uri_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string uri = 4;</code>
     *
     * <pre>
     * http request line not include param 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUriBytes() {
      Object ref = uri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string uid = 5;
    public static final int UID_FIELD_NUMBER = 5;
    private Object uid_;
    /**
     * <code>required string uid = 5;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string uid = 5;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    public String getUid() {
      Object ref = uid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string uid = 5;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      Object ref = uid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string param = 6;
    public static final int PARAM_FIELD_NUMBER = 6;
    private Object param_;
    /**
     * <code>required string param = 6;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    public boolean hasParam() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string param = 6;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    public String getParam() {
      Object ref = param_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          param_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string param = 6;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getParamBytes() {
      Object ref = param_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        param_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string body = 7;
    public static final int BODY_FIELD_NUMBER = 7;
    private Object body_;
    /**
     * <code>required string body = 7;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string body = 7;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    public String getBody() {
      Object ref = body_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          body_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string body = 7;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      Object ref = body_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string ua = 8;
    public static final int UA_FIELD_NUMBER = 8;
    private Object ua_;
    /**
     * <code>required string ua = 8;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    public boolean hasUa() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required string ua = 8;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    public String getUa() {
      Object ref = ua_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ua_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ua = 8;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUaBytes() {
      Object ref = ua_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ua_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 process_time = 9;
    public static final int PROCESS_TIME_FIELD_NUMBER = 9;
    private long processTime_;
    /**
     * <code>required int64 process_time = 9;</code>
     *
     * <pre>
     * </pre>
     */
    public boolean hasProcessTime() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required int64 process_time = 9;</code>
     *
     * <pre>
     * </pre>
     */
    public long getProcessTime() {
      return processTime_;
    }

    // required string refer = 10;
    public static final int REFER_FIELD_NUMBER = 10;
    private Object refer_;
    /**
     * <code>required string refer = 10;</code>
     *
     * <pre>
     * </pre>
     */
    public boolean hasRefer() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required string refer = 10;</code>
     *
     * <pre>
     * </pre>
     */
    public String getRefer() {
      Object ref = refer_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          refer_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string refer = 10;</code>
     *
     * <pre>
     * </pre>
     */
    public com.google.protobuf.ByteString
        getReferBytes() {
      Object ref = refer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        refer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      requestTime_ = 0L;
      ip_ = 0;
      status_ = 0;
      uri_ = "";
      uid_ = "";
      param_ = "";
      body_ = "";
      ua_ = "";
      processTime_ = 0L;
      refer_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRequestTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUri()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasParam()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUa()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProcessTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRefer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, requestTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, ip_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, status_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getUriBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getUidBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getParamBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getBodyBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getUaBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt64(9, processTime_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getReferBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, requestTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, ip_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, status_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getUriBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getUidBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getParamBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getBodyBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getUaBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, processTime_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getReferBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static common_log parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static common_log parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static common_log parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static common_log parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static common_log parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static common_log parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static common_log parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static common_log parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static common_log parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static common_log parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(common_log prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dmp_tracking.common_log}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements common_logOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Logger.internal_static_dmp_tracking_common_log_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Logger.internal_static_dmp_tracking_common_log_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                common_log.class, Builder.class);
      }

      // Construct using dmp_tracking.Logger.common_log.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        requestTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        ip_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        uri_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        uid_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        param_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        body_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        ua_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        processTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        refer_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Logger.internal_static_dmp_tracking_common_log_descriptor;
      }

      public common_log getDefaultInstanceForType() {
        return common_log.getDefaultInstance();
      }

      public common_log build() {
        common_log result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public common_log buildPartial() {
        common_log result = new common_log(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestTime_ = requestTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.uri_ = uri_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.param_ = param_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.body_ = body_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.ua_ = ua_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.processTime_ = processTime_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.refer_ = refer_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof common_log) {
          return mergeFrom((common_log)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(common_log other) {
        if (other == common_log.getDefaultInstance()) return this;
        if (other.hasRequestTime()) {
          setRequestTime(other.getRequestTime());
        }
        if (other.hasIp()) {
          setIp(other.getIp());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasUri()) {
          bitField0_ |= 0x00000008;
          uri_ = other.uri_;
          onChanged();
        }
        if (other.hasUid()) {
          bitField0_ |= 0x00000010;
          uid_ = other.uid_;
          onChanged();
        }
        if (other.hasParam()) {
          bitField0_ |= 0x00000020;
          param_ = other.param_;
          onChanged();
        }
        if (other.hasBody()) {
          bitField0_ |= 0x00000040;
          body_ = other.body_;
          onChanged();
        }
        if (other.hasUa()) {
          bitField0_ |= 0x00000080;
          ua_ = other.ua_;
          onChanged();
        }
        if (other.hasProcessTime()) {
          setProcessTime(other.getProcessTime());
        }
        if (other.hasRefer()) {
          bitField0_ |= 0x00000200;
          refer_ = other.refer_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRequestTime()) {
          
          return false;
        }
        if (!hasIp()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        if (!hasUri()) {
          
          return false;
        }
        if (!hasUid()) {
          
          return false;
        }
        if (!hasParam()) {
          
          return false;
        }
        if (!hasBody()) {
          
          return false;
        }
        if (!hasUa()) {
          
          return false;
        }
        if (!hasProcessTime()) {
          
          return false;
        }
        if (!hasRefer()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        common_log parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (common_log) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 request_time = 1;
      private long requestTime_ ;
      /**
       * <code>required int64 request_time = 1;</code>
       *
       * <pre>
       *unixtime 
       * </pre>
       */
      public boolean hasRequestTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 request_time = 1;</code>
       *
       * <pre>
       *unixtime 
       * </pre>
       */
      public long getRequestTime() {
        return requestTime_;
      }
      /**
       * <code>required int64 request_time = 1;</code>
       *
       * <pre>
       *unixtime 
       * </pre>
       */
      public Builder setRequestTime(long value) {
        bitField0_ |= 0x00000001;
        requestTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 request_time = 1;</code>
       *
       * <pre>
       *unixtime 
       * </pre>
       */
      public Builder clearRequestTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestTime_ = 0L;
        onChanged();
        return this;
      }

      // required uint32 ip = 2;
      private int ip_ ;
      /**
       * <code>required uint32 ip = 2;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 ip = 2;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public int getIp() {
        return ip_;
      }
      /**
       * <code>required uint32 ip = 2;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public Builder setIp(int value) {
        bitField0_ |= 0x00000002;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 ip = 2;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ip_ = 0;
        onChanged();
        return this;
      }

      // required int32 status = 3;
      private int status_ ;
      /**
       * <code>required int32 status = 3;</code>
       *
       * <pre>
       * http status 
       * </pre>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 status = 3;</code>
       *
       * <pre>
       * http status 
       * </pre>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>required int32 status = 3;</code>
       *
       * <pre>
       * http status 
       * </pre>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000004;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 status = 3;</code>
       *
       * <pre>
       * http status 
       * </pre>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = 0;
        onChanged();
        return this;
      }

      // required string uri = 4;
      private Object uri_ = "";
      /**
       * <code>required string uri = 4;</code>
       *
       * <pre>
       * http request line not include param 
       * </pre>
       */
      public boolean hasUri() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string uri = 4;</code>
       *
       * <pre>
       * http request line not include param 
       * </pre>
       */
      public String getUri() {
        Object ref = uri_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uri_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string uri = 4;</code>
       *
       * <pre>
       * http request line not include param 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        Object ref = uri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string uri = 4;</code>
       *
       * <pre>
       * http request line not include param 
       * </pre>
       */
      public Builder setUri(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        uri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string uri = 4;</code>
       *
       * <pre>
       * http request line not include param 
       * </pre>
       */
      public Builder clearUri() {
        bitField0_ = (bitField0_ & ~0x00000008);
        uri_ = getDefaultInstance().getUri();
        onChanged();
        return this;
      }
      /**
       * <code>required string uri = 4;</code>
       *
       * <pre>
       * http request line not include param 
       * </pre>
       */
      public Builder setUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        uri_ = value;
        onChanged();
        return this;
      }

      // required string uid = 5;
      private Object uid_ = "";
      /**
       * <code>required string uid = 5;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string uid = 5;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public String getUid() {
        Object ref = uid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string uid = 5;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string uid = 5;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public Builder setUid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string uid = 5;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <code>required string uid = 5;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        uid_ = value;
        onChanged();
        return this;
      }

      // required string param = 6;
      private Object param_ = "";
      /**
       * <code>required string param = 6;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public boolean hasParam() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string param = 6;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public String getParam() {
        Object ref = param_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          param_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string param = 6;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getParamBytes() {
        Object ref = param_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          param_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string param = 6;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public Builder setParam(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        param_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string param = 6;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public Builder clearParam() {
        bitField0_ = (bitField0_ & ~0x00000020);
        param_ = getDefaultInstance().getParam();
        onChanged();
        return this;
      }
      /**
       * <code>required string param = 6;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public Builder setParamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        param_ = value;
        onChanged();
        return this;
      }

      // required string body = 7;
      private Object body_ = "";
      /**
       * <code>required string body = 7;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string body = 7;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public String getBody() {
        Object ref = body_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string body = 7;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string body = 7;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public Builder setBody(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string body = 7;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000040);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>required string body = 7;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        body_ = value;
        onChanged();
        return this;
      }

      // required string ua = 8;
      private Object ua_ = "";
      /**
       * <code>required string ua = 8;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public boolean hasUa() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string ua = 8;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public String getUa() {
        Object ref = ua_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ua_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string ua = 8;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUaBytes() {
        Object ref = ua_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ua_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ua = 8;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public Builder setUa(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        ua_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ua = 8;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public Builder clearUa() {
        bitField0_ = (bitField0_ & ~0x00000080);
        ua_ = getDefaultInstance().getUa();
        onChanged();
        return this;
      }
      /**
       * <code>required string ua = 8;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public Builder setUaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        ua_ = value;
        onChanged();
        return this;
      }

      // required int64 process_time = 9;
      private long processTime_ ;
      /**
       * <code>required int64 process_time = 9;</code>
       *
       * <pre>
       * </pre>
       */
      public boolean hasProcessTime() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required int64 process_time = 9;</code>
       *
       * <pre>
       * </pre>
       */
      public long getProcessTime() {
        return processTime_;
      }
      /**
       * <code>required int64 process_time = 9;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setProcessTime(long value) {
        bitField0_ |= 0x00000100;
        processTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 process_time = 9;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder clearProcessTime() {
        bitField0_ = (bitField0_ & ~0x00000100);
        processTime_ = 0L;
        onChanged();
        return this;
      }

      // required string refer = 10;
      private Object refer_ = "";
      /**
       * <code>required string refer = 10;</code>
       *
       * <pre>
       * </pre>
       */
      public boolean hasRefer() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required string refer = 10;</code>
       *
       * <pre>
       * </pre>
       */
      public String getRefer() {
        Object ref = refer_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          refer_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string refer = 10;</code>
       *
       * <pre>
       * </pre>
       */
      public com.google.protobuf.ByteString
          getReferBytes() {
        Object ref = refer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          refer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string refer = 10;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setRefer(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        refer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string refer = 10;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder clearRefer() {
        bitField0_ = (bitField0_ & ~0x00000200);
        refer_ = getDefaultInstance().getRefer();
        onChanged();
        return this;
      }
      /**
       * <code>required string refer = 10;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setReferBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        refer_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dmp_tracking.common_log)
    }

    static {
      defaultInstance = new common_log(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:dmp_tracking.common_log)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_dmp_tracking_common_log_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dmp_tracking_common_log_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014logger.proto\022\014dmp_tracking\"\246\001\n\ncommon_" +
      "log\022\024\n\014request_time\030\001 \002(\003\022\n\n\002ip\030\002 \002(\r\022\016\n" +
      "\006status\030\003 \002(\005\022\013\n\003uri\030\004 \002(\t\022\013\n\003uid\030\005 \002(\t\022" +
      "\r\n\005param\030\006 \002(\t\022\014\n\004body\030\007 \002(\t\022\n\n\002ua\030\010 \002(\t" +
      "\022\024\n\014process_time\030\t \002(\003\022\r\n\005refer\030\n \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_dmp_tracking_common_log_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_dmp_tracking_common_log_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_dmp_tracking_common_log_descriptor,
              new String[] { "RequestTime", "Ip", "Status", "Uri", "Uid", "Param", "Body", "Ua", "ProcessTime", "Refer", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
