// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SegmentsLog.proto

package zampdata.records.pb;

public final class SegmentsLog {
  private SegmentsLog() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UcSegmentsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UcSegments)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string zid = 1;</code>
     */
    boolean hasZid();
    /**
     * <code>required string zid = 1;</code>
     */
    String getZid();
    /**
     * <code>required string zid = 1;</code>
     */
    com.google.protobuf.ByteString
        getZidBytes();

    /**
     * <code>required int64 timestamp = 2;</code>
     *
     * <pre>
     *用户访问时间, 请使用unix时间戳
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 2;</code>
     *
     * <pre>
     *用户访问时间, 请使用unix时间戳
     * </pre>
     */
    long getTimestamp();

    /**
     * <code>required string request_id = 3;</code>
     *
     * <pre>
     *segment没有requestid，所以一律填"none"
     * </pre>
     */
    boolean hasRequestId();
    /**
     * <code>required string request_id = 3;</code>
     *
     * <pre>
     *segment没有requestid，所以一律填"none"
     * </pre>
     */
    String getRequestId();
    /**
     * <code>required string request_id = 3;</code>
     *
     * <pre>
     *segment没有requestid，所以一律填"none"
     * </pre>
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <code>required string mobile_id = 4;</code>
     *
     * <pre>
     *移动用户唯一标识，没有时填空
     * </pre>
     */
    boolean hasMobileId();
    /**
     * <code>required string mobile_id = 4;</code>
     *
     * <pre>
     *移动用户唯一标识，没有时填空
     * </pre>
     */
    String getMobileId();
    /**
     * <code>required string mobile_id = 4;</code>
     *
     * <pre>
     *移动用户唯一标识，没有时填空
     * </pre>
     */
    com.google.protobuf.ByteString
        getMobileIdBytes();

    /**
     * <code>required int64 mobile_id_type = 5;</code>
     *
     * <pre>
     * 移动用户ID类型，没有时填-1
     * </pre>
     */
    boolean hasMobileIdType();
    /**
     * <code>required int64 mobile_id_type = 5;</code>
     *
     * <pre>
     * 移动用户ID类型，没有时填-1
     * </pre>
     */
    long getMobileIdType();

    /**
     * <code>required int64 company_id = 6;</code>
     *
     * <pre>
     *广告主ID，没有时填-1
     * </pre>
     */
    boolean hasCompanyId();
    /**
     * <code>required int64 company_id = 6;</code>
     *
     * <pre>
     *广告主ID，没有时填-1
     * </pre>
     */
    long getCompanyId();

    /**
     * <code>required string product_id = 7;</code>
     *
     * <pre>
     *商品ID，没有时填空
     * </pre>
     */
    boolean hasProductId();
    /**
     * <code>required string product_id = 7;</code>
     *
     * <pre>
     *商品ID，没有时填空
     * </pre>
     */
    String getProductId();
    /**
     * <code>required string product_id = 7;</code>
     *
     * <pre>
     *商品ID，没有时填空
     * </pre>
     */
    com.google.protobuf.ByteString
        getProductIdBytes();

    /**
     * <code>required int64 ip = 8;</code>
     *
     * <pre>
     *IP
     * </pre>
     */
    boolean hasIp();
    /**
     * <code>required int64 ip = 8;</code>
     *
     * <pre>
     *IP
     * </pre>
     */
    long getIp();

    /**
     * <code>required string args = 10;</code>
     *
     * <pre>
     *页面上传参数，没有时填空
     * </pre>
     */
    boolean hasArgs();
    /**
     * <code>required string args = 10;</code>
     *
     * <pre>
     *页面上传参数，没有时填空
     * </pre>
     */
    String getArgs();
    /**
     * <code>required string args = 10;</code>
     *
     * <pre>
     *页面上传参数，没有时填空
     * </pre>
     */
    com.google.protobuf.ByteString
        getArgsBytes();

    /**
     * <code>required string url = 11;</code>
     *
     * <pre>
     *用户访问url，没有时填空
     * </pre>
     */
    boolean hasUrl();
    /**
     * <code>required string url = 11;</code>
     *
     * <pre>
     *用户访问url，没有时填空
     * </pre>
     */
    String getUrl();
    /**
     * <code>required string url = 11;</code>
     *
     * <pre>
     *用户访问url，没有时填空
     * </pre>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>required string refer = 12;</code>
     *
     * <pre>
     *refer url，没有时填空
     * </pre>
     */
    boolean hasRefer();
    /**
     * <code>required string refer = 12;</code>
     *
     * <pre>
     *refer url，没有时填空
     * </pre>
     */
    String getRefer();
    /**
     * <code>required string refer = 12;</code>
     *
     * <pre>
     *refer url，没有时填空
     * </pre>
     */
    com.google.protobuf.ByteString
        getReferBytes();

    /**
     * <code>required int32 page_type = 13;</code>
     *
     * <pre>
     *
     * </pre>
     */
    boolean hasPageType();
    /**
     * <code>required int32 page_type = 13;</code>
     *
     * <pre>
     *
     * </pre>
     */
    int getPageType();

    /**
     * <code>required string page_type_name = 14;</code>
     *
     * <pre>
     *页面类型名称，没有时填空
     * </pre>
     */
    boolean hasPageTypeName();
    /**
     * <code>required string page_type_name = 14;</code>
     *
     * <pre>
     *页面类型名称，没有时填空
     * </pre>
     */
    String getPageTypeName();
    /**
     * <code>required string page_type_name = 14;</code>
     *
     * <pre>
     *页面类型名称，没有时填空
     * </pre>
     */
    com.google.protobuf.ByteString
        getPageTypeNameBytes();

    /**
     * <code>repeated int32 segment_ids = 15;</code>
     */
    java.util.List<Integer> getSegmentIdsList();
    /**
     * <code>repeated int32 segment_ids = 15;</code>
     */
    int getSegmentIdsCount();
    /**
     * <code>repeated int32 segment_ids = 15;</code>
     */
    int getSegmentIds(int index);

    /**
     * <code>optional int32 segment_type = 16;</code>
     *
     * <pre>
     *segment来源类型，1：第一方；2：第三方（安全模式）
     * </pre>
     */
    boolean hasSegmentType();
    /**
     * <code>optional int32 segment_type = 16;</code>
     *
     * <pre>
     *segment来源类型，1：第一方；2：第三方（安全模式）
     * </pre>
     */
    int getSegmentType();

    /**
     * <code>optional int32 page_funnel_type = 17;</code>
     *
     * <pre>
     *页面转化漏斗类型
     * </pre>
     */
    boolean hasPageFunnelType();
    /**
     * <code>optional int32 page_funnel_type = 17;</code>
     *
     * <pre>
     *页面转化漏斗类型
     * </pre>
     */
    int getPageFunnelType();
  }
  /**
   * Protobuf type {@code UcSegments}
   */
  public static final class UcSegments extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:UcSegments)
      UcSegmentsOrBuilder {
    // Use UcSegments.newBuilder() to construct.
    private UcSegments(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UcSegments(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UcSegments defaultInstance;
    public static UcSegments getDefaultInstance() {
      return defaultInstance;
    }

    public UcSegments getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UcSegments(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              zid_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              requestId_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              mobileId_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              mobileIdType_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              companyId_ = input.readInt64();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              productId_ = bs;
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              ip_ = input.readInt64();
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              args_ = bs;
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              url_ = bs;
              break;
            }
            case 98: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              refer_ = bs;
              break;
            }
            case 104: {
              bitField0_ |= 0x00000800;
              pageType_ = input.readInt32();
              break;
            }
            case 114: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00001000;
              pageTypeName_ = bs;
              break;
            }
            case 120: {
              if (!((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
                segmentIds_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00002000;
              }
              segmentIds_.add(input.readInt32());
              break;
            }
            case 122: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00002000) == 0x00002000) && input.getBytesUntilLimit() > 0) {
                segmentIds_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00002000;
              }
              while (input.getBytesUntilLimit() > 0) {
                segmentIds_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 128: {
              bitField0_ |= 0x00002000;
              segmentType_ = input.readInt32();
              break;
            }
            case 136: {
              bitField0_ |= 0x00004000;
              pageFunnelType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
          segmentIds_ = java.util.Collections.unmodifiableList(segmentIds_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SegmentsLog.internal_static_UcSegments_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SegmentsLog.internal_static_UcSegments_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UcSegments.class, Builder.class);
    }

    public static com.google.protobuf.Parser<UcSegments> PARSER =
        new com.google.protobuf.AbstractParser<UcSegments>() {
      public UcSegments parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UcSegments(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<UcSegments> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ZID_FIELD_NUMBER = 1;
    private Object zid_;
    /**
     * <code>required string zid = 1;</code>
     */
    public boolean hasZid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string zid = 1;</code>
     */
    public String getZid() {
      Object ref = zid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          zid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string zid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getZidBytes() {
      Object ref = zid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        zid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 2;</code>
     *
     * <pre>
     *用户访问时间, 请使用unix时间戳
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 timestamp = 2;</code>
     *
     * <pre>
     *用户访问时间, 请使用unix时间戳
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int REQUEST_ID_FIELD_NUMBER = 3;
    private Object requestId_;
    /**
     * <code>required string request_id = 3;</code>
     *
     * <pre>
     *segment没有requestid，所以一律填"none"
     * </pre>
     */
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string request_id = 3;</code>
     *
     * <pre>
     *segment没有requestid，所以一律填"none"
     * </pre>
     */
    public String getRequestId() {
      Object ref = requestId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string request_id = 3;</code>
     *
     * <pre>
     *segment没有requestid，所以一律填"none"
     * </pre>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOBILE_ID_FIELD_NUMBER = 4;
    private Object mobileId_;
    /**
     * <code>required string mobile_id = 4;</code>
     *
     * <pre>
     *移动用户唯一标识，没有时填空
     * </pre>
     */
    public boolean hasMobileId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string mobile_id = 4;</code>
     *
     * <pre>
     *移动用户唯一标识，没有时填空
     * </pre>
     */
    public String getMobileId() {
      Object ref = mobileId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mobileId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string mobile_id = 4;</code>
     *
     * <pre>
     *移动用户唯一标识，没有时填空
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMobileIdBytes() {
      Object ref = mobileId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mobileId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOBILE_ID_TYPE_FIELD_NUMBER = 5;
    private long mobileIdType_;
    /**
     * <code>required int64 mobile_id_type = 5;</code>
     *
     * <pre>
     * 移动用户ID类型，没有时填-1
     * </pre>
     */
    public boolean hasMobileIdType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 mobile_id_type = 5;</code>
     *
     * <pre>
     * 移动用户ID类型，没有时填-1
     * </pre>
     */
    public long getMobileIdType() {
      return mobileIdType_;
    }

    public static final int COMPANY_ID_FIELD_NUMBER = 6;
    private long companyId_;
    /**
     * <code>required int64 company_id = 6;</code>
     *
     * <pre>
     *广告主ID，没有时填-1
     * </pre>
     */
    public boolean hasCompanyId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int64 company_id = 6;</code>
     *
     * <pre>
     *广告主ID，没有时填-1
     * </pre>
     */
    public long getCompanyId() {
      return companyId_;
    }

    public static final int PRODUCT_ID_FIELD_NUMBER = 7;
    private Object productId_;
    /**
     * <code>required string product_id = 7;</code>
     *
     * <pre>
     *商品ID，没有时填空
     * </pre>
     */
    public boolean hasProductId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string product_id = 7;</code>
     *
     * <pre>
     *商品ID，没有时填空
     * </pre>
     */
    public String getProductId() {
      Object ref = productId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          productId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string product_id = 7;</code>
     *
     * <pre>
     *商品ID，没有时填空
     * </pre>
     */
    public com.google.protobuf.ByteString
        getProductIdBytes() {
      Object ref = productId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        productId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 8;
    private long ip_;
    /**
     * <code>required int64 ip = 8;</code>
     *
     * <pre>
     *IP
     * </pre>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int64 ip = 8;</code>
     *
     * <pre>
     *IP
     * </pre>
     */
    public long getIp() {
      return ip_;
    }

    public static final int ARGS_FIELD_NUMBER = 10;
    private Object args_;
    /**
     * <code>required string args = 10;</code>
     *
     * <pre>
     *页面上传参数，没有时填空
     * </pre>
     */
    public boolean hasArgs() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required string args = 10;</code>
     *
     * <pre>
     *页面上传参数，没有时填空
     * </pre>
     */
    public String getArgs() {
      Object ref = args_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          args_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string args = 10;</code>
     *
     * <pre>
     *页面上传参数，没有时填空
     * </pre>
     */
    public com.google.protobuf.ByteString
        getArgsBytes() {
      Object ref = args_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        args_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URL_FIELD_NUMBER = 11;
    private Object url_;
    /**
     * <code>required string url = 11;</code>
     *
     * <pre>
     *用户访问url，没有时填空
     * </pre>
     */
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required string url = 11;</code>
     *
     * <pre>
     *用户访问url，没有时填空
     * </pre>
     */
    public String getUrl() {
      Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          url_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string url = 11;</code>
     *
     * <pre>
     *用户访问url，没有时填空
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REFER_FIELD_NUMBER = 12;
    private Object refer_;
    /**
     * <code>required string refer = 12;</code>
     *
     * <pre>
     *refer url，没有时填空
     * </pre>
     */
    public boolean hasRefer() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required string refer = 12;</code>
     *
     * <pre>
     *refer url，没有时填空
     * </pre>
     */
    public String getRefer() {
      Object ref = refer_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          refer_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string refer = 12;</code>
     *
     * <pre>
     *refer url，没有时填空
     * </pre>
     */
    public com.google.protobuf.ByteString
        getReferBytes() {
      Object ref = refer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        refer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAGE_TYPE_FIELD_NUMBER = 13;
    private int pageType_;
    /**
     * <code>required int32 page_type = 13;</code>
     *
     * <pre>
     *
     * </pre>
     */
    public boolean hasPageType() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>required int32 page_type = 13;</code>
     *
     * <pre>
     *
     * </pre>
     */
    public int getPageType() {
      return pageType_;
    }

    public static final int PAGE_TYPE_NAME_FIELD_NUMBER = 14;
    private Object pageTypeName_;
    /**
     * <code>required string page_type_name = 14;</code>
     *
     * <pre>
     *页面类型名称，没有时填空
     * </pre>
     */
    public boolean hasPageTypeName() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>required string page_type_name = 14;</code>
     *
     * <pre>
     *页面类型名称，没有时填空
     * </pre>
     */
    public String getPageTypeName() {
      Object ref = pageTypeName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pageTypeName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string page_type_name = 14;</code>
     *
     * <pre>
     *页面类型名称，没有时填空
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPageTypeNameBytes() {
      Object ref = pageTypeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pageTypeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEGMENT_IDS_FIELD_NUMBER = 15;
    private java.util.List<Integer> segmentIds_;
    /**
     * <code>repeated int32 segment_ids = 15;</code>
     */
    public java.util.List<Integer>
        getSegmentIdsList() {
      return segmentIds_;
    }
    /**
     * <code>repeated int32 segment_ids = 15;</code>
     */
    public int getSegmentIdsCount() {
      return segmentIds_.size();
    }
    /**
     * <code>repeated int32 segment_ids = 15;</code>
     */
    public int getSegmentIds(int index) {
      return segmentIds_.get(index);
    }

    public static final int SEGMENT_TYPE_FIELD_NUMBER = 16;
    private int segmentType_;
    /**
     * <code>optional int32 segment_type = 16;</code>
     *
     * <pre>
     *segment来源类型，1：第一方；2：第三方（安全模式）
     * </pre>
     */
    public boolean hasSegmentType() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional int32 segment_type = 16;</code>
     *
     * <pre>
     *segment来源类型，1：第一方；2：第三方（安全模式）
     * </pre>
     */
    public int getSegmentType() {
      return segmentType_;
    }

    public static final int PAGE_FUNNEL_TYPE_FIELD_NUMBER = 17;
    private int pageFunnelType_;
    /**
     * <code>optional int32 page_funnel_type = 17;</code>
     *
     * <pre>
     *页面转化漏斗类型
     * </pre>
     */
    public boolean hasPageFunnelType() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional int32 page_funnel_type = 17;</code>
     *
     * <pre>
     *页面转化漏斗类型
     * </pre>
     */
    public int getPageFunnelType() {
      return pageFunnelType_;
    }

    private void initFields() {
      zid_ = "";
      timestamp_ = 0L;
      requestId_ = "";
      mobileId_ = "";
      mobileIdType_ = 0L;
      companyId_ = 0L;
      productId_ = "";
      ip_ = 0L;
      args_ = "";
      url_ = "";
      refer_ = "";
      pageType_ = 0;
      pageTypeName_ = "";
      segmentIds_ = java.util.Collections.emptyList();
      segmentType_ = 0;
      pageFunnelType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasZid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequestId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMobileId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMobileIdType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCompanyId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProductId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasArgs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRefer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPageTypeName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getZidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getRequestIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getMobileIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, mobileIdType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, companyId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getProductIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, ip_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(10, getArgsBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(11, getUrlBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(12, getReferBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(13, pageType_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(14, getPageTypeNameBytes());
      }
      for (int i = 0; i < segmentIds_.size(); i++) {
        output.writeInt32(15, segmentIds_.get(i));
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(16, segmentType_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeInt32(17, pageFunnelType_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getZidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getRequestIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getMobileIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, mobileIdType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, companyId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getProductIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, ip_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getArgsBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getUrlBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getReferBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, pageType_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, getPageTypeNameBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < segmentIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(segmentIds_.get(i));
        }
        size += dataSize;
        size += 1 * getSegmentIdsList().size();
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, segmentType_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, pageFunnelType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static UcSegments parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UcSegments parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UcSegments parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UcSegments parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UcSegments parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static UcSegments parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static UcSegments parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static UcSegments parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static UcSegments parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static UcSegments parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(UcSegments prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UcSegments}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UcSegments)
        UcSegmentsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SegmentsLog.internal_static_UcSegments_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SegmentsLog.internal_static_UcSegments_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UcSegments.class, Builder.class);
      }

      // Construct using com.zamplus.protobuf.uclog.SegmentsLog.UcSegments.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        zid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        requestId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        mobileId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        mobileIdType_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        companyId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        productId_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        ip_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        args_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        refer_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        pageType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        pageTypeName_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        segmentIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00002000);
        segmentType_ = 0;
        bitField0_ = (bitField0_ & ~0x00004000);
        pageFunnelType_ = 0;
        bitField0_ = (bitField0_ & ~0x00008000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SegmentsLog.internal_static_UcSegments_descriptor;
      }

      public UcSegments getDefaultInstanceForType() {
        return UcSegments.getDefaultInstance();
      }

      public UcSegments build() {
        UcSegments result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public UcSegments buildPartial() {
        UcSegments result = new UcSegments(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.zid_ = zid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.requestId_ = requestId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.mobileId_ = mobileId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.mobileIdType_ = mobileIdType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.companyId_ = companyId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.productId_ = productId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.args_ = args_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.refer_ = refer_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.pageType_ = pageType_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.pageTypeName_ = pageTypeName_;
        if (((bitField0_ & 0x00002000) == 0x00002000)) {
          segmentIds_ = java.util.Collections.unmodifiableList(segmentIds_);
          bitField0_ = (bitField0_ & ~0x00002000);
        }
        result.segmentIds_ = segmentIds_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.segmentType_ = segmentType_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.pageFunnelType_ = pageFunnelType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UcSegments) {
          return mergeFrom((UcSegments)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UcSegments other) {
        if (other == UcSegments.getDefaultInstance()) return this;
        if (other.hasZid()) {
          bitField0_ |= 0x00000001;
          zid_ = other.zid_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasRequestId()) {
          bitField0_ |= 0x00000004;
          requestId_ = other.requestId_;
          onChanged();
        }
        if (other.hasMobileId()) {
          bitField0_ |= 0x00000008;
          mobileId_ = other.mobileId_;
          onChanged();
        }
        if (other.hasMobileIdType()) {
          setMobileIdType(other.getMobileIdType());
        }
        if (other.hasCompanyId()) {
          setCompanyId(other.getCompanyId());
        }
        if (other.hasProductId()) {
          bitField0_ |= 0x00000040;
          productId_ = other.productId_;
          onChanged();
        }
        if (other.hasIp()) {
          setIp(other.getIp());
        }
        if (other.hasArgs()) {
          bitField0_ |= 0x00000100;
          args_ = other.args_;
          onChanged();
        }
        if (other.hasUrl()) {
          bitField0_ |= 0x00000200;
          url_ = other.url_;
          onChanged();
        }
        if (other.hasRefer()) {
          bitField0_ |= 0x00000400;
          refer_ = other.refer_;
          onChanged();
        }
        if (other.hasPageType()) {
          setPageType(other.getPageType());
        }
        if (other.hasPageTypeName()) {
          bitField0_ |= 0x00001000;
          pageTypeName_ = other.pageTypeName_;
          onChanged();
        }
        if (!other.segmentIds_.isEmpty()) {
          if (segmentIds_.isEmpty()) {
            segmentIds_ = other.segmentIds_;
            bitField0_ = (bitField0_ & ~0x00002000);
          } else {
            ensureSegmentIdsIsMutable();
            segmentIds_.addAll(other.segmentIds_);
          }
          onChanged();
        }
        if (other.hasSegmentType()) {
          setSegmentType(other.getSegmentType());
        }
        if (other.hasPageFunnelType()) {
          setPageFunnelType(other.getPageFunnelType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasZid()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasRequestId()) {
          
          return false;
        }
        if (!hasMobileId()) {
          
          return false;
        }
        if (!hasMobileIdType()) {
          
          return false;
        }
        if (!hasCompanyId()) {
          
          return false;
        }
        if (!hasProductId()) {
          
          return false;
        }
        if (!hasIp()) {
          
          return false;
        }
        if (!hasArgs()) {
          
          return false;
        }
        if (!hasUrl()) {
          
          return false;
        }
        if (!hasRefer()) {
          
          return false;
        }
        if (!hasPageType()) {
          
          return false;
        }
        if (!hasPageTypeName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UcSegments parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UcSegments) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object zid_ = "";
      /**
       * <code>required string zid = 1;</code>
       */
      public boolean hasZid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string zid = 1;</code>
       */
      public String getZid() {
        Object ref = zid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            zid_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string zid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getZidBytes() {
        Object ref = zid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          zid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string zid = 1;</code>
       */
      public Builder setZid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        zid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string zid = 1;</code>
       */
      public Builder clearZid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        zid_ = getDefaultInstance().getZid();
        onChanged();
        return this;
      }
      /**
       * <code>required string zid = 1;</code>
       */
      public Builder setZidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        zid_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 2;</code>
       *
       * <pre>
       *用户访问时间, 请使用unix时间戳
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 timestamp = 2;</code>
       *
       * <pre>
       *用户访问时间, 请使用unix时间戳
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 2;</code>
       *
       * <pre>
       *用户访问时间, 请使用unix时间戳
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 2;</code>
       *
       * <pre>
       *用户访问时间, 请使用unix时间戳
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private Object requestId_ = "";
      /**
       * <code>required string request_id = 3;</code>
       *
       * <pre>
       *segment没有requestid，所以一律填"none"
       * </pre>
       */
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string request_id = 3;</code>
       *
       * <pre>
       *segment没有requestid，所以一律填"none"
       * </pre>
       */
      public String getRequestId() {
        Object ref = requestId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            requestId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string request_id = 3;</code>
       *
       * <pre>
       *segment没有requestid，所以一律填"none"
       * </pre>
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string request_id = 3;</code>
       *
       * <pre>
       *segment没有requestid，所以一律填"none"
       * </pre>
       */
      public Builder setRequestId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string request_id = 3;</code>
       *
       * <pre>
       *segment没有requestid，所以一律填"none"
       * </pre>
       */
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <code>required string request_id = 3;</code>
       *
       * <pre>
       *segment没有requestid，所以一律填"none"
       * </pre>
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        requestId_ = value;
        onChanged();
        return this;
      }

      private Object mobileId_ = "";
      /**
       * <code>required string mobile_id = 4;</code>
       *
       * <pre>
       *移动用户唯一标识，没有时填空
       * </pre>
       */
      public boolean hasMobileId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string mobile_id = 4;</code>
       *
       * <pre>
       *移动用户唯一标识，没有时填空
       * </pre>
       */
      public String getMobileId() {
        Object ref = mobileId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mobileId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string mobile_id = 4;</code>
       *
       * <pre>
       *移动用户唯一标识，没有时填空
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMobileIdBytes() {
        Object ref = mobileId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mobileId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string mobile_id = 4;</code>
       *
       * <pre>
       *移动用户唯一标识，没有时填空
       * </pre>
       */
      public Builder setMobileId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        mobileId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string mobile_id = 4;</code>
       *
       * <pre>
       *移动用户唯一标识，没有时填空
       * </pre>
       */
      public Builder clearMobileId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mobileId_ = getDefaultInstance().getMobileId();
        onChanged();
        return this;
      }
      /**
       * <code>required string mobile_id = 4;</code>
       *
       * <pre>
       *移动用户唯一标识，没有时填空
       * </pre>
       */
      public Builder setMobileIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        mobileId_ = value;
        onChanged();
        return this;
      }

      private long mobileIdType_ ;
      /**
       * <code>required int64 mobile_id_type = 5;</code>
       *
       * <pre>
       * 移动用户ID类型，没有时填-1
       * </pre>
       */
      public boolean hasMobileIdType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 mobile_id_type = 5;</code>
       *
       * <pre>
       * 移动用户ID类型，没有时填-1
       * </pre>
       */
      public long getMobileIdType() {
        return mobileIdType_;
      }
      /**
       * <code>required int64 mobile_id_type = 5;</code>
       *
       * <pre>
       * 移动用户ID类型，没有时填-1
       * </pre>
       */
      public Builder setMobileIdType(long value) {
        bitField0_ |= 0x00000010;
        mobileIdType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 mobile_id_type = 5;</code>
       *
       * <pre>
       * 移动用户ID类型，没有时填-1
       * </pre>
       */
      public Builder clearMobileIdType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        mobileIdType_ = 0L;
        onChanged();
        return this;
      }

      private long companyId_ ;
      /**
       * <code>required int64 company_id = 6;</code>
       *
       * <pre>
       *广告主ID，没有时填-1
       * </pre>
       */
      public boolean hasCompanyId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int64 company_id = 6;</code>
       *
       * <pre>
       *广告主ID，没有时填-1
       * </pre>
       */
      public long getCompanyId() {
        return companyId_;
      }
      /**
       * <code>required int64 company_id = 6;</code>
       *
       * <pre>
       *广告主ID，没有时填-1
       * </pre>
       */
      public Builder setCompanyId(long value) {
        bitField0_ |= 0x00000020;
        companyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 company_id = 6;</code>
       *
       * <pre>
       *广告主ID，没有时填-1
       * </pre>
       */
      public Builder clearCompanyId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        companyId_ = 0L;
        onChanged();
        return this;
      }

      private Object productId_ = "";
      /**
       * <code>required string product_id = 7;</code>
       *
       * <pre>
       *商品ID，没有时填空
       * </pre>
       */
      public boolean hasProductId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string product_id = 7;</code>
       *
       * <pre>
       *商品ID，没有时填空
       * </pre>
       */
      public String getProductId() {
        Object ref = productId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            productId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string product_id = 7;</code>
       *
       * <pre>
       *商品ID，没有时填空
       * </pre>
       */
      public com.google.protobuf.ByteString
          getProductIdBytes() {
        Object ref = productId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          productId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string product_id = 7;</code>
       *
       * <pre>
       *商品ID，没有时填空
       * </pre>
       */
      public Builder setProductId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        productId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string product_id = 7;</code>
       *
       * <pre>
       *商品ID，没有时填空
       * </pre>
       */
      public Builder clearProductId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        productId_ = getDefaultInstance().getProductId();
        onChanged();
        return this;
      }
      /**
       * <code>required string product_id = 7;</code>
       *
       * <pre>
       *商品ID，没有时填空
       * </pre>
       */
      public Builder setProductIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        productId_ = value;
        onChanged();
        return this;
      }

      private long ip_ ;
      /**
       * <code>required int64 ip = 8;</code>
       *
       * <pre>
       *IP
       * </pre>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int64 ip = 8;</code>
       *
       * <pre>
       *IP
       * </pre>
       */
      public long getIp() {
        return ip_;
      }
      /**
       * <code>required int64 ip = 8;</code>
       *
       * <pre>
       *IP
       * </pre>
       */
      public Builder setIp(long value) {
        bitField0_ |= 0x00000080;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 ip = 8;</code>
       *
       * <pre>
       *IP
       * </pre>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000080);
        ip_ = 0L;
        onChanged();
        return this;
      }

      private Object args_ = "";
      /**
       * <code>required string args = 10;</code>
       *
       * <pre>
       *页面上传参数，没有时填空
       * </pre>
       */
      public boolean hasArgs() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required string args = 10;</code>
       *
       * <pre>
       *页面上传参数，没有时填空
       * </pre>
       */
      public String getArgs() {
        Object ref = args_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            args_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string args = 10;</code>
       *
       * <pre>
       *页面上传参数，没有时填空
       * </pre>
       */
      public com.google.protobuf.ByteString
          getArgsBytes() {
        Object ref = args_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          args_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string args = 10;</code>
       *
       * <pre>
       *页面上传参数，没有时填空
       * </pre>
       */
      public Builder setArgs(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        args_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string args = 10;</code>
       *
       * <pre>
       *页面上传参数，没有时填空
       * </pre>
       */
      public Builder clearArgs() {
        bitField0_ = (bitField0_ & ~0x00000100);
        args_ = getDefaultInstance().getArgs();
        onChanged();
        return this;
      }
      /**
       * <code>required string args = 10;</code>
       *
       * <pre>
       *页面上传参数，没有时填空
       * </pre>
       */
      public Builder setArgsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        args_ = value;
        onChanged();
        return this;
      }

      private Object url_ = "";
      /**
       * <code>required string url = 11;</code>
       *
       * <pre>
       *用户访问url，没有时填空
       * </pre>
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required string url = 11;</code>
       *
       * <pre>
       *用户访问url，没有时填空
       * </pre>
       */
      public String getUrl() {
        Object ref = url_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            url_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string url = 11;</code>
       *
       * <pre>
       *用户访问url，没有时填空
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string url = 11;</code>
       *
       * <pre>
       *用户访问url，没有时填空
       * </pre>
       */
      public Builder setUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string url = 11;</code>
       *
       * <pre>
       *用户访问url，没有时填空
       * </pre>
       */
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000200);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>required string url = 11;</code>
       *
       * <pre>
       *用户访问url，没有时填空
       * </pre>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        url_ = value;
        onChanged();
        return this;
      }

      private Object refer_ = "";
      /**
       * <code>required string refer = 12;</code>
       *
       * <pre>
       *refer url，没有时填空
       * </pre>
       */
      public boolean hasRefer() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required string refer = 12;</code>
       *
       * <pre>
       *refer url，没有时填空
       * </pre>
       */
      public String getRefer() {
        Object ref = refer_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            refer_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string refer = 12;</code>
       *
       * <pre>
       *refer url，没有时填空
       * </pre>
       */
      public com.google.protobuf.ByteString
          getReferBytes() {
        Object ref = refer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          refer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string refer = 12;</code>
       *
       * <pre>
       *refer url，没有时填空
       * </pre>
       */
      public Builder setRefer(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        refer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string refer = 12;</code>
       *
       * <pre>
       *refer url，没有时填空
       * </pre>
       */
      public Builder clearRefer() {
        bitField0_ = (bitField0_ & ~0x00000400);
        refer_ = getDefaultInstance().getRefer();
        onChanged();
        return this;
      }
      /**
       * <code>required string refer = 12;</code>
       *
       * <pre>
       *refer url，没有时填空
       * </pre>
       */
      public Builder setReferBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        refer_ = value;
        onChanged();
        return this;
      }

      private int pageType_ ;
      /**
       * <code>required int32 page_type = 13;</code>
       *
       * <pre>
       *
       * </pre>
       */
      public boolean hasPageType() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required int32 page_type = 13;</code>
       *
       * <pre>
       *
       * </pre>
       */
      public int getPageType() {
        return pageType_;
      }
      /**
       * <code>required int32 page_type = 13;</code>
       *
       * <pre>
       *
       * </pre>
       */
      public Builder setPageType(int value) {
        bitField0_ |= 0x00000800;
        pageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 page_type = 13;</code>
       *
       * <pre>
       *
       * </pre>
       */
      public Builder clearPageType() {
        bitField0_ = (bitField0_ & ~0x00000800);
        pageType_ = 0;
        onChanged();
        return this;
      }

      private Object pageTypeName_ = "";
      /**
       * <code>required string page_type_name = 14;</code>
       *
       * <pre>
       *页面类型名称，没有时填空
       * </pre>
       */
      public boolean hasPageTypeName() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>required string page_type_name = 14;</code>
       *
       * <pre>
       *页面类型名称，没有时填空
       * </pre>
       */
      public String getPageTypeName() {
        Object ref = pageTypeName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pageTypeName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string page_type_name = 14;</code>
       *
       * <pre>
       *页面类型名称，没有时填空
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPageTypeNameBytes() {
        Object ref = pageTypeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          pageTypeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string page_type_name = 14;</code>
       *
       * <pre>
       *页面类型名称，没有时填空
       * </pre>
       */
      public Builder setPageTypeName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        pageTypeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string page_type_name = 14;</code>
       *
       * <pre>
       *页面类型名称，没有时填空
       * </pre>
       */
      public Builder clearPageTypeName() {
        bitField0_ = (bitField0_ & ~0x00001000);
        pageTypeName_ = getDefaultInstance().getPageTypeName();
        onChanged();
        return this;
      }
      /**
       * <code>required string page_type_name = 14;</code>
       *
       * <pre>
       *页面类型名称，没有时填空
       * </pre>
       */
      public Builder setPageTypeNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        pageTypeName_ = value;
        onChanged();
        return this;
      }

      private java.util.List<Integer> segmentIds_ = java.util.Collections.emptyList();
      private void ensureSegmentIdsIsMutable() {
        if (!((bitField0_ & 0x00002000) == 0x00002000)) {
          segmentIds_ = new java.util.ArrayList<Integer>(segmentIds_);
          bitField0_ |= 0x00002000;
         }
      }
      /**
       * <code>repeated int32 segment_ids = 15;</code>
       */
      public java.util.List<Integer>
          getSegmentIdsList() {
        return java.util.Collections.unmodifiableList(segmentIds_);
      }
      /**
       * <code>repeated int32 segment_ids = 15;</code>
       */
      public int getSegmentIdsCount() {
        return segmentIds_.size();
      }
      /**
       * <code>repeated int32 segment_ids = 15;</code>
       */
      public int getSegmentIds(int index) {
        return segmentIds_.get(index);
      }
      /**
       * <code>repeated int32 segment_ids = 15;</code>
       */
      public Builder setSegmentIds(
          int index, int value) {
        ensureSegmentIdsIsMutable();
        segmentIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 segment_ids = 15;</code>
       */
      public Builder addSegmentIds(int value) {
        ensureSegmentIdsIsMutable();
        segmentIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 segment_ids = 15;</code>
       */
      public Builder addAllSegmentIds(
          Iterable<? extends Integer> values) {
        ensureSegmentIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, segmentIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 segment_ids = 15;</code>
       */
      public Builder clearSegmentIds() {
        segmentIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00002000);
        onChanged();
        return this;
      }

      private int segmentType_ ;
      /**
       * <code>optional int32 segment_type = 16;</code>
       *
       * <pre>
       *segment来源类型，1：第一方；2：第三方（安全模式）
       * </pre>
       */
      public boolean hasSegmentType() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional int32 segment_type = 16;</code>
       *
       * <pre>
       *segment来源类型，1：第一方；2：第三方（安全模式）
       * </pre>
       */
      public int getSegmentType() {
        return segmentType_;
      }
      /**
       * <code>optional int32 segment_type = 16;</code>
       *
       * <pre>
       *segment来源类型，1：第一方；2：第三方（安全模式）
       * </pre>
       */
      public Builder setSegmentType(int value) {
        bitField0_ |= 0x00004000;
        segmentType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 segment_type = 16;</code>
       *
       * <pre>
       *segment来源类型，1：第一方；2：第三方（安全模式）
       * </pre>
       */
      public Builder clearSegmentType() {
        bitField0_ = (bitField0_ & ~0x00004000);
        segmentType_ = 0;
        onChanged();
        return this;
      }

      private int pageFunnelType_ ;
      /**
       * <code>optional int32 page_funnel_type = 17;</code>
       *
       * <pre>
       *页面转化漏斗类型
       * </pre>
       */
      public boolean hasPageFunnelType() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional int32 page_funnel_type = 17;</code>
       *
       * <pre>
       *页面转化漏斗类型
       * </pre>
       */
      public int getPageFunnelType() {
        return pageFunnelType_;
      }
      /**
       * <code>optional int32 page_funnel_type = 17;</code>
       *
       * <pre>
       *页面转化漏斗类型
       * </pre>
       */
      public Builder setPageFunnelType(int value) {
        bitField0_ |= 0x00008000;
        pageFunnelType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 page_funnel_type = 17;</code>
       *
       * <pre>
       *页面转化漏斗类型
       * </pre>
       */
      public Builder clearPageFunnelType() {
        bitField0_ = (bitField0_ & ~0x00008000);
        pageFunnelType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:UcSegments)
    }

    static {
      defaultInstance = new UcSegments(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:UcSegments)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UcSegments_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UcSegments_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021SegmentsLog.proto\"\271\002\n\nUcSegments\022\013\n\003zi" +
      "d\030\001 \002(\t\022\021\n\ttimestamp\030\002 \002(\003\022\022\n\nrequest_id" +
      "\030\003 \002(\t\022\021\n\tmobile_id\030\004 \002(\t\022\026\n\016mobile_id_t" +
      "ype\030\005 \002(\003\022\022\n\ncompany_id\030\006 \002(\003\022\022\n\nproduct" +
      "_id\030\007 \002(\t\022\n\n\002ip\030\010 \002(\003\022\014\n\004args\030\n \002(\t\022\013\n\003u" +
      "rl\030\013 \002(\t\022\r\n\005refer\030\014 \002(\t\022\021\n\tpage_type\030\r \002" +
      "(\005\022\026\n\016page_type_name\030\016 \002(\t\022\023\n\013segment_id" +
      "s\030\017 \003(\005\022\024\n\014segment_type\030\020 \001(\005\022\030\n\020page_fu" +
      "nnel_type\030\021 \001(\005B\034\n\032com.zamplus.protobuf." +
      "uclog"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_UcSegments_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UcSegments_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UcSegments_descriptor,
        new String[] { "Zid", "Timestamp", "RequestId", "MobileId", "MobileIdType", "CompanyId", "ProductId", "Ip", "Args", "Url", "Refer", "PageType", "PageTypeName", "SegmentIds", "SegmentType", "PageFunnelType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
