// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/mk.proto

package tracking;

public final class Mk {
  private Mk() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface mkOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 project_id = 1;
    /**
     * <code>required int32 project_id = 1;</code>
     */
    boolean hasProjectId();
    /**
     * <code>required int32 project_id = 1;</code>
     */
    int getProjectId();

    // required int32 account_id = 2;
    /**
     * <code>required int32 account_id = 2;</code>
     */
    boolean hasAccountId();
    /**
     * <code>required int32 account_id = 2;</code>
     */
    int getAccountId();

    // required int32 vendor_id = 3;
    /**
     * <code>required int32 vendor_id = 3;</code>
     */
    boolean hasVendorId();
    /**
     * <code>required int32 vendor_id = 3;</code>
     */
    int getVendorId();

    // required int64 campaign_id = 4;
    /**
     * <code>required int64 campaign_id = 4;</code>
     */
    boolean hasCampaignId();
    /**
     * <code>required int64 campaign_id = 4;</code>
     */
    long getCampaignId();

    // required int64 adgroup_id = 5;
    /**
     * <code>required int64 adgroup_id = 5;</code>
     */
    boolean hasAdgroupId();
    /**
     * <code>required int64 adgroup_id = 5;</code>
     */
    long getAdgroupId();

    // required int64 ad_id = 6;
    /**
     * <code>required int64 ad_id = 6;</code>
     */
    boolean hasAdId();
    /**
     * <code>required int64 ad_id = 6;</code>
     */
    long getAdId();

    // repeated int64 material_id = 7;
    /**
     * <code>repeated int64 material_id = 7;</code>
     */
    java.util.List<java.lang.Long> getMaterialIdList();
    /**
     * <code>repeated int64 material_id = 7;</code>
     */
    int getMaterialIdCount();
    /**
     * <code>repeated int64 material_id = 7;</code>
     */
    long getMaterialId(int index);

    // optional int64 template_id = 8;
    /**
     * <code>optional int64 template_id = 8;</code>
     */
    boolean hasTemplateId();
    /**
     * <code>optional int64 template_id = 8;</code>
     */
    long getTemplateId();

    // optional string material_type = 9 [default = "1"];
    /**
     * <code>optional string material_type = 9 [default = "1"];</code>
     */
    boolean hasMaterialType();
    /**
     * <code>optional string material_type = 9 [default = "1"];</code>
     */
    java.lang.String getMaterialType();
    /**
     * <code>optional string material_type = 9 [default = "1"];</code>
     */
    com.google.protobuf.ByteString
        getMaterialTypeBytes();

    // required string request_id = 10;
    /**
     * <code>required string request_id = 10;</code>
     */
    boolean hasRequestId();
    /**
     * <code>required string request_id = 10;</code>
     */
    java.lang.String getRequestId();
    /**
     * <code>required string request_id = 10;</code>
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    // required string adx_user_id = 11;
    /**
     * <code>required string adx_user_id = 11;</code>
     */
    boolean hasAdxUserId();
    /**
     * <code>required string adx_user_id = 11;</code>
     */
    java.lang.String getAdxUserId();
    /**
     * <code>required string adx_user_id = 11;</code>
     */
    com.google.protobuf.ByteString
        getAdxUserIdBytes();

    // required string adslot_id = 12;
    /**
     * <code>required string adslot_id = 12;</code>
     */
    boolean hasAdslotId();
    /**
     * <code>required string adslot_id = 12;</code>
     */
    java.lang.String getAdslotId();
    /**
     * <code>required string adslot_id = 12;</code>
     */
    com.google.protobuf.ByteString
        getAdslotIdBytes();

    // required int64 time_stamp = 13;
    /**
     * <code>required int64 time_stamp = 13;</code>
     */
    boolean hasTimeStamp();
    /**
     * <code>required int64 time_stamp = 13;</code>
     */
    long getTimeStamp();

    // required int32 random = 14;
    /**
     * <code>required int32 random = 14;</code>
     */
    boolean hasRandom();
    /**
     * <code>required int32 random = 14;</code>
     */
    int getRandom();

    // required string secret_key = 15;
    /**
     * <code>required string secret_key = 15;</code>
     */
    boolean hasSecretKey();
    /**
     * <code>required string secret_key = 15;</code>
     */
    java.lang.String getSecretKey();
    /**
     * <code>required string secret_key = 15;</code>
     */
    com.google.protobuf.ByteString
        getSecretKeyBytes();

    // optional string idfa = 16;
    /**
     * <code>optional string idfa = 16;</code>
     */
    boolean hasIdfa();
    /**
     * <code>optional string idfa = 16;</code>
     */
    java.lang.String getIdfa();
    /**
     * <code>optional string idfa = 16;</code>
     */
    com.google.protobuf.ByteString
        getIdfaBytes();

    // optional string hash_idfa = 17;
    /**
     * <code>optional string hash_idfa = 17;</code>
     */
    boolean hasHashIdfa();
    /**
     * <code>optional string hash_idfa = 17;</code>
     */
    java.lang.String getHashIdfa();
    /**
     * <code>optional string hash_idfa = 17;</code>
     */
    com.google.protobuf.ByteString
        getHashIdfaBytes();

    // required string location_url = 18;
    /**
     * <code>required string location_url = 18;</code>
     *
     * <pre>
     * if mobile app,this value is appid
     * </pre>
     */
    boolean hasLocationUrl();
    /**
     * <code>required string location_url = 18;</code>
     *
     * <pre>
     * if mobile app,this value is appid
     * </pre>
     */
    java.lang.String getLocationUrl();
    /**
     * <code>required string location_url = 18;</code>
     *
     * <pre>
     * if mobile app,this value is appid
     * </pre>
     */
    com.google.protobuf.ByteString
        getLocationUrlBytes();
  }
  /**
   * Protobuf type {@code tracking.mk}
   */
  public static final class mk extends
      com.google.protobuf.GeneratedMessage
      implements mkOrBuilder {
    // Use mk.newBuilder() to construct.
    private mk(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private mk(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final mk defaultInstance;
    public static mk getDefaultInstance() {
      return defaultInstance;
    }

    public mk getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private mk(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              projectId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              accountId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              vendorId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              campaignId_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              adgroupId_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              adId_ = input.readInt64();
              break;
            }
            case 56: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                materialId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000040;
              }
              materialId_.add(input.readInt64());
              break;
            }
            case 58: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040) && input.getBytesUntilLimit() > 0) {
                materialId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000040;
              }
              while (input.getBytesUntilLimit() > 0) {
                materialId_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 64: {
              bitField0_ |= 0x00000040;
              templateId_ = input.readInt64();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000080;
              materialType_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000100;
              requestId_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000200;
              adxUserId_ = input.readBytes();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000400;
              adslotId_ = input.readBytes();
              break;
            }
            case 104: {
              bitField0_ |= 0x00000800;
              timeStamp_ = input.readInt64();
              break;
            }
            case 112: {
              bitField0_ |= 0x00001000;
              random_ = input.readInt32();
              break;
            }
            case 122: {
              bitField0_ |= 0x00002000;
              secretKey_ = input.readBytes();
              break;
            }
            case 130: {
              bitField0_ |= 0x00004000;
              idfa_ = input.readBytes();
              break;
            }
            case 138: {
              bitField0_ |= 0x00008000;
              hashIdfa_ = input.readBytes();
              break;
            }
            case 146: {
              bitField0_ |= 0x00010000;
              locationUrl_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          materialId_ = java.util.Collections.unmodifiableList(materialId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tracking.Mk.internal_static_tracking_mk_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tracking.Mk.internal_static_tracking_mk_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tracking.Mk.mk.class, tracking.Mk.mk.Builder.class);
    }

    public static com.google.protobuf.Parser<mk> PARSER =
        new com.google.protobuf.AbstractParser<mk>() {
      public mk parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new mk(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<mk> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 project_id = 1;
    public static final int PROJECT_ID_FIELD_NUMBER = 1;
    private int projectId_;
    /**
     * <code>required int32 project_id = 1;</code>
     */
    public boolean hasProjectId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 project_id = 1;</code>
     */
    public int getProjectId() {
      return projectId_;
    }

    // required int32 account_id = 2;
    public static final int ACCOUNT_ID_FIELD_NUMBER = 2;
    private int accountId_;
    /**
     * <code>required int32 account_id = 2;</code>
     */
    public boolean hasAccountId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 account_id = 2;</code>
     */
    public int getAccountId() {
      return accountId_;
    }

    // required int32 vendor_id = 3;
    public static final int VENDOR_ID_FIELD_NUMBER = 3;
    private int vendorId_;
    /**
     * <code>required int32 vendor_id = 3;</code>
     */
    public boolean hasVendorId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 vendor_id = 3;</code>
     */
    public int getVendorId() {
      return vendorId_;
    }

    // required int64 campaign_id = 4;
    public static final int CAMPAIGN_ID_FIELD_NUMBER = 4;
    private long campaignId_;
    /**
     * <code>required int64 campaign_id = 4;</code>
     */
    public boolean hasCampaignId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 campaign_id = 4;</code>
     */
    public long getCampaignId() {
      return campaignId_;
    }

    // required int64 adgroup_id = 5;
    public static final int ADGROUP_ID_FIELD_NUMBER = 5;
    private long adgroupId_;
    /**
     * <code>required int64 adgroup_id = 5;</code>
     */
    public boolean hasAdgroupId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 adgroup_id = 5;</code>
     */
    public long getAdgroupId() {
      return adgroupId_;
    }

    // required int64 ad_id = 6;
    public static final int AD_ID_FIELD_NUMBER = 6;
    private long adId_;
    /**
     * <code>required int64 ad_id = 6;</code>
     */
    public boolean hasAdId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int64 ad_id = 6;</code>
     */
    public long getAdId() {
      return adId_;
    }

    // repeated int64 material_id = 7;
    public static final int MATERIAL_ID_FIELD_NUMBER = 7;
    private java.util.List<java.lang.Long> materialId_;
    /**
     * <code>repeated int64 material_id = 7;</code>
     */
    public java.util.List<java.lang.Long>
        getMaterialIdList() {
      return materialId_;
    }
    /**
     * <code>repeated int64 material_id = 7;</code>
     */
    public int getMaterialIdCount() {
      return materialId_.size();
    }
    /**
     * <code>repeated int64 material_id = 7;</code>
     */
    public long getMaterialId(int index) {
      return materialId_.get(index);
    }

    // optional int64 template_id = 8;
    public static final int TEMPLATE_ID_FIELD_NUMBER = 8;
    private long templateId_;
    /**
     * <code>optional int64 template_id = 8;</code>
     */
    public boolean hasTemplateId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int64 template_id = 8;</code>
     */
    public long getTemplateId() {
      return templateId_;
    }

    // optional string material_type = 9 [default = "1"];
    public static final int MATERIAL_TYPE_FIELD_NUMBER = 9;
    private java.lang.Object materialType_;
    /**
     * <code>optional string material_type = 9 [default = "1"];</code>
     */
    public boolean hasMaterialType() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string material_type = 9 [default = "1"];</code>
     */
    public java.lang.String getMaterialType() {
      java.lang.Object ref = materialType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          materialType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string material_type = 9 [default = "1"];</code>
     */
    public com.google.protobuf.ByteString
        getMaterialTypeBytes() {
      java.lang.Object ref = materialType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        materialType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string request_id = 10;
    public static final int REQUEST_ID_FIELD_NUMBER = 10;
    private java.lang.Object requestId_;
    /**
     * <code>required string request_id = 10;</code>
     */
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required string request_id = 10;</code>
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string request_id = 10;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string adx_user_id = 11;
    public static final int ADX_USER_ID_FIELD_NUMBER = 11;
    private java.lang.Object adxUserId_;
    /**
     * <code>required string adx_user_id = 11;</code>
     */
    public boolean hasAdxUserId() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required string adx_user_id = 11;</code>
     */
    public java.lang.String getAdxUserId() {
      java.lang.Object ref = adxUserId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          adxUserId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string adx_user_id = 11;</code>
     */
    public com.google.protobuf.ByteString
        getAdxUserIdBytes() {
      java.lang.Object ref = adxUserId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        adxUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string adslot_id = 12;
    public static final int ADSLOT_ID_FIELD_NUMBER = 12;
    private java.lang.Object adslotId_;
    /**
     * <code>required string adslot_id = 12;</code>
     */
    public boolean hasAdslotId() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required string adslot_id = 12;</code>
     */
    public java.lang.String getAdslotId() {
      java.lang.Object ref = adslotId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          adslotId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string adslot_id = 12;</code>
     */
    public com.google.protobuf.ByteString
        getAdslotIdBytes() {
      java.lang.Object ref = adslotId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        adslotId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 time_stamp = 13;
    public static final int TIME_STAMP_FIELD_NUMBER = 13;
    private long timeStamp_;
    /**
     * <code>required int64 time_stamp = 13;</code>
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>required int64 time_stamp = 13;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }

    // required int32 random = 14;
    public static final int RANDOM_FIELD_NUMBER = 14;
    private int random_;
    /**
     * <code>required int32 random = 14;</code>
     */
    public boolean hasRandom() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>required int32 random = 14;</code>
     */
    public int getRandom() {
      return random_;
    }

    // required string secret_key = 15;
    public static final int SECRET_KEY_FIELD_NUMBER = 15;
    private java.lang.Object secretKey_;
    /**
     * <code>required string secret_key = 15;</code>
     */
    public boolean hasSecretKey() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>required string secret_key = 15;</code>
     */
    public java.lang.String getSecretKey() {
      java.lang.Object ref = secretKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          secretKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string secret_key = 15;</code>
     */
    public com.google.protobuf.ByteString
        getSecretKeyBytes() {
      java.lang.Object ref = secretKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secretKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string idfa = 16;
    public static final int IDFA_FIELD_NUMBER = 16;
    private java.lang.Object idfa_;
    /**
     * <code>optional string idfa = 16;</code>
     */
    public boolean hasIdfa() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional string idfa = 16;</code>
     */
    public java.lang.String getIdfa() {
      java.lang.Object ref = idfa_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          idfa_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string idfa = 16;</code>
     */
    public com.google.protobuf.ByteString
        getIdfaBytes() {
      java.lang.Object ref = idfa_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idfa_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string hash_idfa = 17;
    public static final int HASH_IDFA_FIELD_NUMBER = 17;
    private java.lang.Object hashIdfa_;
    /**
     * <code>optional string hash_idfa = 17;</code>
     */
    public boolean hasHashIdfa() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional string hash_idfa = 17;</code>
     */
    public java.lang.String getHashIdfa() {
      java.lang.Object ref = hashIdfa_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hashIdfa_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string hash_idfa = 17;</code>
     */
    public com.google.protobuf.ByteString
        getHashIdfaBytes() {
      java.lang.Object ref = hashIdfa_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hashIdfa_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string location_url = 18;
    public static final int LOCATION_URL_FIELD_NUMBER = 18;
    private java.lang.Object locationUrl_;
    /**
     * <code>required string location_url = 18;</code>
     *
     * <pre>
     * if mobile app,this value is appid
     * </pre>
     */
    public boolean hasLocationUrl() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>required string location_url = 18;</code>
     *
     * <pre>
     * if mobile app,this value is appid
     * </pre>
     */
    public java.lang.String getLocationUrl() {
      java.lang.Object ref = locationUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          locationUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string location_url = 18;</code>
     *
     * <pre>
     * if mobile app,this value is appid
     * </pre>
     */
    public com.google.protobuf.ByteString
        getLocationUrlBytes() {
      java.lang.Object ref = locationUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        locationUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      projectId_ = 0;
      accountId_ = 0;
      vendorId_ = 0;
      campaignId_ = 0L;
      adgroupId_ = 0L;
      adId_ = 0L;
      materialId_ = java.util.Collections.emptyList();
      templateId_ = 0L;
      materialType_ = "1";
      requestId_ = "";
      adxUserId_ = "";
      adslotId_ = "";
      timeStamp_ = 0L;
      random_ = 0;
      secretKey_ = "";
      idfa_ = "";
      hashIdfa_ = "";
      locationUrl_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasProjectId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccountId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVendorId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCampaignId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAdgroupId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAdId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequestId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAdxUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAdslotId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRandom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSecretKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocationUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, projectId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, accountId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, vendorId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, campaignId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, adgroupId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, adId_);
      }
      for (int i = 0; i < materialId_.size(); i++) {
        output.writeInt64(7, materialId_.get(i));
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(8, templateId_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(9, getMaterialTypeBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(10, getRequestIdBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(11, getAdxUserIdBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(12, getAdslotIdBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt64(13, timeStamp_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(14, random_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeBytes(15, getSecretKeyBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeBytes(16, getIdfaBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeBytes(17, getHashIdfaBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeBytes(18, getLocationUrlBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, projectId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, accountId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, vendorId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, campaignId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, adgroupId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, adId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < materialId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(materialId_.get(i));
        }
        size += dataSize;
        size += 1 * getMaterialIdList().size();
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, templateId_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getMaterialTypeBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getRequestIdBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getAdxUserIdBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getAdslotIdBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(13, timeStamp_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, random_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, getSecretKeyBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, getIdfaBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(17, getHashIdfaBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(18, getLocationUrlBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static tracking.Mk.mk parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tracking.Mk.mk parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tracking.Mk.mk parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tracking.Mk.mk parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tracking.Mk.mk parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tracking.Mk.mk parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static tracking.Mk.mk parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static tracking.Mk.mk parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static tracking.Mk.mk parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tracking.Mk.mk parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tracking.Mk.mk prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tracking.mk}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements tracking.Mk.mkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tracking.Mk.internal_static_tracking_mk_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tracking.Mk.internal_static_tracking_mk_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tracking.Mk.mk.class, tracking.Mk.mk.Builder.class);
      }

      // Construct using tracking.Mk.mk.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        projectId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        accountId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        vendorId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        campaignId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        adgroupId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        adId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        materialId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        templateId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        materialType_ = "1";
        bitField0_ = (bitField0_ & ~0x00000100);
        requestId_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        adxUserId_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        adslotId_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        timeStamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00001000);
        random_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        secretKey_ = "";
        bitField0_ = (bitField0_ & ~0x00004000);
        idfa_ = "";
        bitField0_ = (bitField0_ & ~0x00008000);
        hashIdfa_ = "";
        bitField0_ = (bitField0_ & ~0x00010000);
        locationUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00020000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tracking.Mk.internal_static_tracking_mk_descriptor;
      }

      public tracking.Mk.mk getDefaultInstanceForType() {
        return tracking.Mk.mk.getDefaultInstance();
      }

      public tracking.Mk.mk build() {
        tracking.Mk.mk result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tracking.Mk.mk buildPartial() {
        tracking.Mk.mk result = new tracking.Mk.mk(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.projectId_ = projectId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.accountId_ = accountId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.vendorId_ = vendorId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.campaignId_ = campaignId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.adgroupId_ = adgroupId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.adId_ = adId_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          materialId_ = java.util.Collections.unmodifiableList(materialId_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.materialId_ = materialId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.templateId_ = templateId_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000080;
        }
        result.materialType_ = materialType_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000100;
        }
        result.requestId_ = requestId_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000200;
        }
        result.adxUserId_ = adxUserId_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000400;
        }
        result.adslotId_ = adslotId_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00000800;
        }
        result.timeStamp_ = timeStamp_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.random_ = random_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.secretKey_ = secretKey_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.idfa_ = idfa_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.hashIdfa_ = hashIdfa_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.locationUrl_ = locationUrl_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tracking.Mk.mk) {
          return mergeFrom((tracking.Mk.mk)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tracking.Mk.mk other) {
        if (other == tracking.Mk.mk.getDefaultInstance()) return this;
        if (other.hasProjectId()) {
          setProjectId(other.getProjectId());
        }
        if (other.hasAccountId()) {
          setAccountId(other.getAccountId());
        }
        if (other.hasVendorId()) {
          setVendorId(other.getVendorId());
        }
        if (other.hasCampaignId()) {
          setCampaignId(other.getCampaignId());
        }
        if (other.hasAdgroupId()) {
          setAdgroupId(other.getAdgroupId());
        }
        if (other.hasAdId()) {
          setAdId(other.getAdId());
        }
        if (!other.materialId_.isEmpty()) {
          if (materialId_.isEmpty()) {
            materialId_ = other.materialId_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureMaterialIdIsMutable();
            materialId_.addAll(other.materialId_);
          }
          onChanged();
        }
        if (other.hasTemplateId()) {
          setTemplateId(other.getTemplateId());
        }
        if (other.hasMaterialType()) {
          bitField0_ |= 0x00000100;
          materialType_ = other.materialType_;
          onChanged();
        }
        if (other.hasRequestId()) {
          bitField0_ |= 0x00000200;
          requestId_ = other.requestId_;
          onChanged();
        }
        if (other.hasAdxUserId()) {
          bitField0_ |= 0x00000400;
          adxUserId_ = other.adxUserId_;
          onChanged();
        }
        if (other.hasAdslotId()) {
          bitField0_ |= 0x00000800;
          adslotId_ = other.adslotId_;
          onChanged();
        }
        if (other.hasTimeStamp()) {
          setTimeStamp(other.getTimeStamp());
        }
        if (other.hasRandom()) {
          setRandom(other.getRandom());
        }
        if (other.hasSecretKey()) {
          bitField0_ |= 0x00004000;
          secretKey_ = other.secretKey_;
          onChanged();
        }
        if (other.hasIdfa()) {
          bitField0_ |= 0x00008000;
          idfa_ = other.idfa_;
          onChanged();
        }
        if (other.hasHashIdfa()) {
          bitField0_ |= 0x00010000;
          hashIdfa_ = other.hashIdfa_;
          onChanged();
        }
        if (other.hasLocationUrl()) {
          bitField0_ |= 0x00020000;
          locationUrl_ = other.locationUrl_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasProjectId()) {
          
          return false;
        }
        if (!hasAccountId()) {
          
          return false;
        }
        if (!hasVendorId()) {
          
          return false;
        }
        if (!hasCampaignId()) {
          
          return false;
        }
        if (!hasAdgroupId()) {
          
          return false;
        }
        if (!hasAdId()) {
          
          return false;
        }
        if (!hasRequestId()) {
          
          return false;
        }
        if (!hasAdxUserId()) {
          
          return false;
        }
        if (!hasAdslotId()) {
          
          return false;
        }
        if (!hasTimeStamp()) {
          
          return false;
        }
        if (!hasRandom()) {
          
          return false;
        }
        if (!hasSecretKey()) {
          
          return false;
        }
        if (!hasLocationUrl()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tracking.Mk.mk parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tracking.Mk.mk) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 project_id = 1;
      private int projectId_ ;
      /**
       * <code>required int32 project_id = 1;</code>
       */
      public boolean hasProjectId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 project_id = 1;</code>
       */
      public int getProjectId() {
        return projectId_;
      }
      /**
       * <code>required int32 project_id = 1;</code>
       */
      public Builder setProjectId(int value) {
        bitField0_ |= 0x00000001;
        projectId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 project_id = 1;</code>
       */
      public Builder clearProjectId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        projectId_ = 0;
        onChanged();
        return this;
      }

      // required int32 account_id = 2;
      private int accountId_ ;
      /**
       * <code>required int32 account_id = 2;</code>
       */
      public boolean hasAccountId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 account_id = 2;</code>
       */
      public int getAccountId() {
        return accountId_;
      }
      /**
       * <code>required int32 account_id = 2;</code>
       */
      public Builder setAccountId(int value) {
        bitField0_ |= 0x00000002;
        accountId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 account_id = 2;</code>
       */
      public Builder clearAccountId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        accountId_ = 0;
        onChanged();
        return this;
      }

      // required int32 vendor_id = 3;
      private int vendorId_ ;
      /**
       * <code>required int32 vendor_id = 3;</code>
       */
      public boolean hasVendorId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 vendor_id = 3;</code>
       */
      public int getVendorId() {
        return vendorId_;
      }
      /**
       * <code>required int32 vendor_id = 3;</code>
       */
      public Builder setVendorId(int value) {
        bitField0_ |= 0x00000004;
        vendorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 vendor_id = 3;</code>
       */
      public Builder clearVendorId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        vendorId_ = 0;
        onChanged();
        return this;
      }

      // required int64 campaign_id = 4;
      private long campaignId_ ;
      /**
       * <code>required int64 campaign_id = 4;</code>
       */
      public boolean hasCampaignId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 campaign_id = 4;</code>
       */
      public long getCampaignId() {
        return campaignId_;
      }
      /**
       * <code>required int64 campaign_id = 4;</code>
       */
      public Builder setCampaignId(long value) {
        bitField0_ |= 0x00000008;
        campaignId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 campaign_id = 4;</code>
       */
      public Builder clearCampaignId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        campaignId_ = 0L;
        onChanged();
        return this;
      }

      // required int64 adgroup_id = 5;
      private long adgroupId_ ;
      /**
       * <code>required int64 adgroup_id = 5;</code>
       */
      public boolean hasAdgroupId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 adgroup_id = 5;</code>
       */
      public long getAdgroupId() {
        return adgroupId_;
      }
      /**
       * <code>required int64 adgroup_id = 5;</code>
       */
      public Builder setAdgroupId(long value) {
        bitField0_ |= 0x00000010;
        adgroupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 adgroup_id = 5;</code>
       */
      public Builder clearAdgroupId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        adgroupId_ = 0L;
        onChanged();
        return this;
      }

      // required int64 ad_id = 6;
      private long adId_ ;
      /**
       * <code>required int64 ad_id = 6;</code>
       */
      public boolean hasAdId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int64 ad_id = 6;</code>
       */
      public long getAdId() {
        return adId_;
      }
      /**
       * <code>required int64 ad_id = 6;</code>
       */
      public Builder setAdId(long value) {
        bitField0_ |= 0x00000020;
        adId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 ad_id = 6;</code>
       */
      public Builder clearAdId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        adId_ = 0L;
        onChanged();
        return this;
      }

      // repeated int64 material_id = 7;
      private java.util.List<java.lang.Long> materialId_ = java.util.Collections.emptyList();
      private void ensureMaterialIdIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          materialId_ = new java.util.ArrayList<java.lang.Long>(materialId_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated int64 material_id = 7;</code>
       */
      public java.util.List<java.lang.Long>
          getMaterialIdList() {
        return java.util.Collections.unmodifiableList(materialId_);
      }
      /**
       * <code>repeated int64 material_id = 7;</code>
       */
      public int getMaterialIdCount() {
        return materialId_.size();
      }
      /**
       * <code>repeated int64 material_id = 7;</code>
       */
      public long getMaterialId(int index) {
        return materialId_.get(index);
      }
      /**
       * <code>repeated int64 material_id = 7;</code>
       */
      public Builder setMaterialId(
          int index, long value) {
        ensureMaterialIdIsMutable();
        materialId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 material_id = 7;</code>
       */
      public Builder addMaterialId(long value) {
        ensureMaterialIdIsMutable();
        materialId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 material_id = 7;</code>
       */
      public Builder addAllMaterialId(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureMaterialIdIsMutable();
        super.addAll(values, materialId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 material_id = 7;</code>
       */
      public Builder clearMaterialId() {
        materialId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }

      // optional int64 template_id = 8;
      private long templateId_ ;
      /**
       * <code>optional int64 template_id = 8;</code>
       */
      public boolean hasTemplateId() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int64 template_id = 8;</code>
       */
      public long getTemplateId() {
        return templateId_;
      }
      /**
       * <code>optional int64 template_id = 8;</code>
       */
      public Builder setTemplateId(long value) {
        bitField0_ |= 0x00000080;
        templateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 template_id = 8;</code>
       */
      public Builder clearTemplateId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        templateId_ = 0L;
        onChanged();
        return this;
      }

      // optional string material_type = 9 [default = "1"];
      private java.lang.Object materialType_ = "1";
      /**
       * <code>optional string material_type = 9 [default = "1"];</code>
       */
      public boolean hasMaterialType() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string material_type = 9 [default = "1"];</code>
       */
      public java.lang.String getMaterialType() {
        java.lang.Object ref = materialType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          materialType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string material_type = 9 [default = "1"];</code>
       */
      public com.google.protobuf.ByteString
          getMaterialTypeBytes() {
        java.lang.Object ref = materialType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          materialType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string material_type = 9 [default = "1"];</code>
       */
      public Builder setMaterialType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        materialType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string material_type = 9 [default = "1"];</code>
       */
      public Builder clearMaterialType() {
        bitField0_ = (bitField0_ & ~0x00000100);
        materialType_ = getDefaultInstance().getMaterialType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string material_type = 9 [default = "1"];</code>
       */
      public Builder setMaterialTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        materialType_ = value;
        onChanged();
        return this;
      }

      // required string request_id = 10;
      private java.lang.Object requestId_ = "";
      /**
       * <code>required string request_id = 10;</code>
       */
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required string request_id = 10;</code>
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string request_id = 10;</code>
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string request_id = 10;</code>
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string request_id = 10;</code>
       */
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000200);
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <code>required string request_id = 10;</code>
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        requestId_ = value;
        onChanged();
        return this;
      }

      // required string adx_user_id = 11;
      private java.lang.Object adxUserId_ = "";
      /**
       * <code>required string adx_user_id = 11;</code>
       */
      public boolean hasAdxUserId() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required string adx_user_id = 11;</code>
       */
      public java.lang.String getAdxUserId() {
        java.lang.Object ref = adxUserId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          adxUserId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string adx_user_id = 11;</code>
       */
      public com.google.protobuf.ByteString
          getAdxUserIdBytes() {
        java.lang.Object ref = adxUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          adxUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string adx_user_id = 11;</code>
       */
      public Builder setAdxUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        adxUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string adx_user_id = 11;</code>
       */
      public Builder clearAdxUserId() {
        bitField0_ = (bitField0_ & ~0x00000400);
        adxUserId_ = getDefaultInstance().getAdxUserId();
        onChanged();
        return this;
      }
      /**
       * <code>required string adx_user_id = 11;</code>
       */
      public Builder setAdxUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        adxUserId_ = value;
        onChanged();
        return this;
      }

      // required string adslot_id = 12;
      private java.lang.Object adslotId_ = "";
      /**
       * <code>required string adslot_id = 12;</code>
       */
      public boolean hasAdslotId() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required string adslot_id = 12;</code>
       */
      public java.lang.String getAdslotId() {
        java.lang.Object ref = adslotId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          adslotId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string adslot_id = 12;</code>
       */
      public com.google.protobuf.ByteString
          getAdslotIdBytes() {
        java.lang.Object ref = adslotId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          adslotId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string adslot_id = 12;</code>
       */
      public Builder setAdslotId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        adslotId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string adslot_id = 12;</code>
       */
      public Builder clearAdslotId() {
        bitField0_ = (bitField0_ & ~0x00000800);
        adslotId_ = getDefaultInstance().getAdslotId();
        onChanged();
        return this;
      }
      /**
       * <code>required string adslot_id = 12;</code>
       */
      public Builder setAdslotIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        adslotId_ = value;
        onChanged();
        return this;
      }

      // required int64 time_stamp = 13;
      private long timeStamp_ ;
      /**
       * <code>required int64 time_stamp = 13;</code>
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>required int64 time_stamp = 13;</code>
       */
      public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>required int64 time_stamp = 13;</code>
       */
      public Builder setTimeStamp(long value) {
        bitField0_ |= 0x00001000;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 time_stamp = 13;</code>
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00001000);
        timeStamp_ = 0L;
        onChanged();
        return this;
      }

      // required int32 random = 14;
      private int random_ ;
      /**
       * <code>required int32 random = 14;</code>
       */
      public boolean hasRandom() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>required int32 random = 14;</code>
       */
      public int getRandom() {
        return random_;
      }
      /**
       * <code>required int32 random = 14;</code>
       */
      public Builder setRandom(int value) {
        bitField0_ |= 0x00002000;
        random_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 random = 14;</code>
       */
      public Builder clearRandom() {
        bitField0_ = (bitField0_ & ~0x00002000);
        random_ = 0;
        onChanged();
        return this;
      }

      // required string secret_key = 15;
      private java.lang.Object secretKey_ = "";
      /**
       * <code>required string secret_key = 15;</code>
       */
      public boolean hasSecretKey() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>required string secret_key = 15;</code>
       */
      public java.lang.String getSecretKey() {
        java.lang.Object ref = secretKey_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          secretKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string secret_key = 15;</code>
       */
      public com.google.protobuf.ByteString
          getSecretKeyBytes() {
        java.lang.Object ref = secretKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          secretKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string secret_key = 15;</code>
       */
      public Builder setSecretKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        secretKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string secret_key = 15;</code>
       */
      public Builder clearSecretKey() {
        bitField0_ = (bitField0_ & ~0x00004000);
        secretKey_ = getDefaultInstance().getSecretKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string secret_key = 15;</code>
       */
      public Builder setSecretKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        secretKey_ = value;
        onChanged();
        return this;
      }

      // optional string idfa = 16;
      private java.lang.Object idfa_ = "";
      /**
       * <code>optional string idfa = 16;</code>
       */
      public boolean hasIdfa() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional string idfa = 16;</code>
       */
      public java.lang.String getIdfa() {
        java.lang.Object ref = idfa_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          idfa_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string idfa = 16;</code>
       */
      public com.google.protobuf.ByteString
          getIdfaBytes() {
        java.lang.Object ref = idfa_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idfa_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string idfa = 16;</code>
       */
      public Builder setIdfa(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        idfa_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string idfa = 16;</code>
       */
      public Builder clearIdfa() {
        bitField0_ = (bitField0_ & ~0x00008000);
        idfa_ = getDefaultInstance().getIdfa();
        onChanged();
        return this;
      }
      /**
       * <code>optional string idfa = 16;</code>
       */
      public Builder setIdfaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        idfa_ = value;
        onChanged();
        return this;
      }

      // optional string hash_idfa = 17;
      private java.lang.Object hashIdfa_ = "";
      /**
       * <code>optional string hash_idfa = 17;</code>
       */
      public boolean hasHashIdfa() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>optional string hash_idfa = 17;</code>
       */
      public java.lang.String getHashIdfa() {
        java.lang.Object ref = hashIdfa_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          hashIdfa_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string hash_idfa = 17;</code>
       */
      public com.google.protobuf.ByteString
          getHashIdfaBytes() {
        java.lang.Object ref = hashIdfa_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hashIdfa_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string hash_idfa = 17;</code>
       */
      public Builder setHashIdfa(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
        hashIdfa_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string hash_idfa = 17;</code>
       */
      public Builder clearHashIdfa() {
        bitField0_ = (bitField0_ & ~0x00010000);
        hashIdfa_ = getDefaultInstance().getHashIdfa();
        onChanged();
        return this;
      }
      /**
       * <code>optional string hash_idfa = 17;</code>
       */
      public Builder setHashIdfaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
        hashIdfa_ = value;
        onChanged();
        return this;
      }

      // required string location_url = 18;
      private java.lang.Object locationUrl_ = "";
      /**
       * <code>required string location_url = 18;</code>
       *
       * <pre>
       * if mobile app,this value is appid
       * </pre>
       */
      public boolean hasLocationUrl() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      /**
       * <code>required string location_url = 18;</code>
       *
       * <pre>
       * if mobile app,this value is appid
       * </pre>
       */
      public java.lang.String getLocationUrl() {
        java.lang.Object ref = locationUrl_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          locationUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string location_url = 18;</code>
       *
       * <pre>
       * if mobile app,this value is appid
       * </pre>
       */
      public com.google.protobuf.ByteString
          getLocationUrlBytes() {
        java.lang.Object ref = locationUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          locationUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string location_url = 18;</code>
       *
       * <pre>
       * if mobile app,this value is appid
       * </pre>
       */
      public Builder setLocationUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
        locationUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string location_url = 18;</code>
       *
       * <pre>
       * if mobile app,this value is appid
       * </pre>
       */
      public Builder clearLocationUrl() {
        bitField0_ = (bitField0_ & ~0x00020000);
        locationUrl_ = getDefaultInstance().getLocationUrl();
        onChanged();
        return this;
      }
      /**
       * <code>required string location_url = 18;</code>
       *
       * <pre>
       * if mobile app,this value is appid
       * </pre>
       */
      public Builder setLocationUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00020000;
        locationUrl_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tracking.mk)
    }

    static {
      defaultInstance = new mk(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tracking.mk)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tracking_mk_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tracking_mk_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032src/main/protobuf/mk.proto\022\010tracking\"\346" +
      "\002\n\002mk\022\022\n\nproject_id\030\001 \002(\005\022\022\n\naccount_id\030" +
      "\002 \002(\005\022\021\n\tvendor_id\030\003 \002(\005\022\023\n\013campaign_id\030" +
      "\004 \002(\003\022\022\n\nadgroup_id\030\005 \002(\003\022\r\n\005ad_id\030\006 \002(\003" +
      "\022\023\n\013material_id\030\007 \003(\003\022\023\n\013template_id\030\010 \001" +
      "(\003\022\030\n\rmaterial_type\030\t \001(\t:\0011\022\022\n\nrequest_" +
      "id\030\n \002(\t\022\023\n\013adx_user_id\030\013 \002(\t\022\021\n\tadslot_" +
      "id\030\014 \002(\t\022\022\n\ntime_stamp\030\r \002(\003\022\016\n\006random\030\016" +
      " \002(\005\022\022\n\nsecret_key\030\017 \002(\t\022\014\n\004idfa\030\020 \001(\t\022\021" +
      "\n\thash_idfa\030\021 \001(\t\022\024\n\014location_url\030\022 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tracking_mk_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tracking_mk_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tracking_mk_descriptor,
              new java.lang.String[] { "ProjectId", "AccountId", "VendorId", "CampaignId", "AdgroupId", "AdId", "MaterialId", "TemplateId", "MaterialType", "RequestId", "AdxUserId", "AdslotId", "TimeStamp", "Random", "SecretKey", "Idfa", "HashIdfa", "LocationUrl", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
