// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IdsLog.proto

package com.zamplus.protobuf.uclog;

public final class IdsLog {
  private IdsLog() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PidOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 venderId = 1;
    /**
     * <code>required int32 venderId = 1;</code>
     *
     * <pre>
     *vender id
     * </pre>
     */
    boolean hasVenderId();
    /**
     * <code>required int32 venderId = 1;</code>
     *
     * <pre>
     *vender id
     * </pre>
     */
    int getVenderId();

    // required string id = 2;
    /**
     * <code>required string id = 2;</code>
     *
     * <pre>
     *id值
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required string id = 2;</code>
     *
     * <pre>
     *id值
     * </pre>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 2;</code>
     *
     * <pre>
     *id值
     * </pre>
     */
    com.google.protobuf.ByteString
        getIdBytes();
  }
  /**
   * Protobuf type {@code Pid}
   */
  public static final class Pid extends
      com.google.protobuf.GeneratedMessage
      implements PidOrBuilder {
    // Use Pid.newBuilder() to construct.
    private Pid(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Pid(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Pid defaultInstance;
    public static Pid getDefaultInstance() {
      return defaultInstance;
    }

    public Pid getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Pid(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              venderId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              id_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_Pid_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_Pid_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
                  com.zamplus.protobuf.uclog.IdsLog.Pid.class, com.zamplus.protobuf.uclog.IdsLog.Pid.Builder.class);
    }

    public static com.google.protobuf.Parser<Pid> PARSER =
        new com.google.protobuf.AbstractParser<Pid>() {
      public Pid parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Pid(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Pid> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 venderId = 1;
    public static final int VENDERID_FIELD_NUMBER = 1;
    private int venderId_;
    /**
     * <code>required int32 venderId = 1;</code>
     *
     * <pre>
     *vender id
     * </pre>
     */
    public boolean hasVenderId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 venderId = 1;</code>
     *
     * <pre>
     *vender id
     * </pre>
     */
    public int getVenderId() {
      return venderId_;
    }

    // required string id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private java.lang.Object id_;
    /**
     * <code>required string id = 2;</code>
     *
     * <pre>
     *id值
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string id = 2;</code>
     *
     * <pre>
     *id值
     * </pre>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 2;</code>
     *
     * <pre>
     *id值
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      venderId_ = 0;
      id_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasVenderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, venderId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, venderId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zamplus.protobuf.uclog.IdsLog.Pid parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zamplus.protobuf.uclog.IdsLog.Pid parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zamplus.protobuf.uclog.IdsLog.Pid parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zamplus.protobuf.uclog.IdsLog.Pid parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zamplus.protobuf.uclog.IdsLog.Pid parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zamplus.protobuf.uclog.IdsLog.Pid parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zamplus.protobuf.uclog.IdsLog.Pid parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zamplus.protobuf.uclog.IdsLog.Pid parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zamplus.protobuf.uclog.IdsLog.Pid parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zamplus.protobuf.uclog.IdsLog.Pid parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zamplus.protobuf.uclog.IdsLog.Pid prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Pid}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zamplus.protobuf.uclog.IdsLog.PidOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_Pid_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_Pid_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    com.zamplus.protobuf.uclog.IdsLog.Pid.class, com.zamplus.protobuf.uclog.IdsLog.Pid.Builder.class);
      }

      // Construct using com.zamplus.protobuf.uclog.IdsLog.Pid.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        venderId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_Pid_descriptor;
      }

      public com.zamplus.protobuf.uclog.IdsLog.Pid getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      public com.zamplus.protobuf.uclog.IdsLog.Pid build() {
        com.zamplus.protobuf.uclog.IdsLog.Pid result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zamplus.protobuf.uclog.IdsLog.Pid buildPartial() {
        com.zamplus.protobuf.uclog.IdsLog.Pid result = new com.zamplus.protobuf.uclog.IdsLog.Pid(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.venderId_ = venderId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zamplus.protobuf.uclog.IdsLog.Pid) {
          return mergeFrom((com.zamplus.protobuf.uclog.IdsLog.Pid)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zamplus.protobuf.uclog.IdsLog.Pid other) {
        if (other == getDefaultInstance()) return this;
        if (other.hasVenderId()) {
          setVenderId(other.getVenderId());
        }
        if (other.hasId()) {
          bitField0_ |= 0x00000002;
          id_ = other.id_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVenderId()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zamplus.protobuf.uclog.IdsLog.Pid parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zamplus.protobuf.uclog.IdsLog.Pid) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 venderId = 1;
      private int venderId_ ;
      /**
       * <code>required int32 venderId = 1;</code>
       *
       * <pre>
       *vender id
       * </pre>
       */
      public boolean hasVenderId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 venderId = 1;</code>
       *
       * <pre>
       *vender id
       * </pre>
       */
      public int getVenderId() {
        return venderId_;
      }
      /**
       * <code>required int32 venderId = 1;</code>
       *
       * <pre>
       *vender id
       * </pre>
       */
      public Builder setVenderId(int value) {
        bitField0_ |= 0x00000001;
        venderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 venderId = 1;</code>
       *
       * <pre>
       *vender id
       * </pre>
       */
      public Builder clearVenderId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        venderId_ = 0;
        onChanged();
        return this;
      }

      // required string id = 2;
      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 2;</code>
       *
       * <pre>
       *id值
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string id = 2;</code>
       *
       * <pre>
       *id值
       * </pre>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 2;</code>
       *
       * <pre>
       *id值
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 2;</code>
       *
       * <pre>
       *id值
       * </pre>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 2;</code>
       *
       * <pre>
       *id值
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 2;</code>
       *
       * <pre>
       *id值
       * </pre>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Pid)
    }

    static {
      defaultInstance = new Pid(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Pid)
  }

  public interface PlatformIdsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string zid = 1;
    /**
     * <code>required string zid = 1;</code>
     *
     * <pre>
     *zid
     * </pre>
     */
    boolean hasZid();
    /**
     * <code>required string zid = 1;</code>
     *
     * <pre>
     *zid
     * </pre>
     */
    java.lang.String getZid();
    /**
     * <code>required string zid = 1;</code>
     *
     * <pre>
     *zid
     * </pre>
     */
    com.google.protobuf.ByteString
        getZidBytes();

    // repeated .Pid pids = 2;
    /**
     * <code>repeated .Pid pids = 2;</code>
     *
     * <pre>
     *各平台id列表
     * </pre>
     */
    java.util.List<com.zamplus.protobuf.uclog.IdsLog.Pid> 
        getPidsList();
    /**
     * <code>repeated .Pid pids = 2;</code>
     *
     * <pre>
     *各平台id列表
     * </pre>
     */
    com.zamplus.protobuf.uclog.IdsLog.Pid getPids(int index);
    /**
     * <code>repeated .Pid pids = 2;</code>
     *
     * <pre>
     *各平台id列表
     * </pre>
     */
    int getPidsCount();
    /**
     * <code>repeated .Pid pids = 2;</code>
     *
     * <pre>
     *各平台id列表
     * </pre>
     */
    java.util.List<? extends com.zamplus.protobuf.uclog.IdsLog.PidOrBuilder> 
        getPidsOrBuilderList();
    /**
     * <code>repeated .Pid pids = 2;</code>
     *
     * <pre>
     *各平台id列表
     * </pre>
     */
    com.zamplus.protobuf.uclog.IdsLog.PidOrBuilder getPidsOrBuilder(
        int index);

    // required int64 timestamp = 3;
    /**
     * <code>required int64 timestamp = 3;</code>
     *
     * <pre>
     *tracking记录的用户访问时间戳
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 3;</code>
     *
     * <pre>
     *tracking记录的用户访问时间戳
     * </pre>
     */
    long getTimestamp();

    // required int32 adverId = 4;
    /**
     * <code>required int32 adverId = 4;</code>
     *
     * <pre>
     *广告主id
     * </pre>
     */
    boolean hasAdverId();
    /**
     * <code>required int32 adverId = 4;</code>
     *
     * <pre>
     *广告主id
     * </pre>
     */
    int getAdverId();
  }
  /**
   * Protobuf type {@code PlatformIds}
   */
  public static final class PlatformIds extends
      com.google.protobuf.GeneratedMessage
      implements PlatformIdsOrBuilder {
    // Use PlatformIds.newBuilder() to construct.
    private PlatformIds(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlatformIds(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlatformIds defaultInstance;
    public static PlatformIds getDefaultInstance() {
      return defaultInstance;
    }

    public PlatformIds getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlatformIds(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              zid_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                pids_ = new java.util.ArrayList<com.zamplus.protobuf.uclog.IdsLog.Pid>();
                mutable_bitField0_ |= 0x00000002;
              }
              pids_.add(input.readMessage(com.zamplus.protobuf.uclog.IdsLog.Pid.PARSER, extensionRegistry));
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              adverId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          pids_ = java.util.Collections.unmodifiableList(pids_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_PlatformIds_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_PlatformIds_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
                  com.zamplus.protobuf.uclog.IdsLog.PlatformIds.class, com.zamplus.protobuf.uclog.IdsLog.PlatformIds.Builder.class);
    }

    public static com.google.protobuf.Parser<PlatformIds> PARSER =
        new com.google.protobuf.AbstractParser<PlatformIds>() {
      public PlatformIds parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlatformIds(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlatformIds> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string zid = 1;
    public static final int ZID_FIELD_NUMBER = 1;
    private java.lang.Object zid_;
    /**
     * <code>required string zid = 1;</code>
     *
     * <pre>
     *zid
     * </pre>
     */
    public boolean hasZid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string zid = 1;</code>
     *
     * <pre>
     *zid
     * </pre>
     */
    public java.lang.String getZid() {
      java.lang.Object ref = zid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          zid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string zid = 1;</code>
     *
     * <pre>
     *zid
     * </pre>
     */
    public com.google.protobuf.ByteString
        getZidBytes() {
      java.lang.Object ref = zid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .Pid pids = 2;
    public static final int PIDS_FIELD_NUMBER = 2;
    private java.util.List<com.zamplus.protobuf.uclog.IdsLog.Pid> pids_;
    /**
     * <code>repeated .Pid pids = 2;</code>
     *
     * <pre>
     *各平台id列表
     * </pre>
     */
    public java.util.List<com.zamplus.protobuf.uclog.IdsLog.Pid> getPidsList() {
      return pids_;
    }
    /**
     * <code>repeated .Pid pids = 2;</code>
     *
     * <pre>
     *各平台id列表
     * </pre>
     */
    public java.util.List<? extends com.zamplus.protobuf.uclog.IdsLog.PidOrBuilder> 
        getPidsOrBuilderList() {
      return pids_;
    }
    /**
     * <code>repeated .Pid pids = 2;</code>
     *
     * <pre>
     *各平台id列表
     * </pre>
     */
    public int getPidsCount() {
      return pids_.size();
    }
    /**
     * <code>repeated .Pid pids = 2;</code>
     *
     * <pre>
     *各平台id列表
     * </pre>
     */
    public com.zamplus.protobuf.uclog.IdsLog.Pid getPids(int index) {
      return pids_.get(index);
    }
    /**
     * <code>repeated .Pid pids = 2;</code>
     *
     * <pre>
     *各平台id列表
     * </pre>
     */
    public com.zamplus.protobuf.uclog.IdsLog.PidOrBuilder getPidsOrBuilder(
        int index) {
      return pids_.get(index);
    }

    // required int64 timestamp = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 3;</code>
     *
     * <pre>
     *tracking记录的用户访问时间戳
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 timestamp = 3;</code>
     *
     * <pre>
     *tracking记录的用户访问时间戳
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    // required int32 adverId = 4;
    public static final int ADVERID_FIELD_NUMBER = 4;
    private int adverId_;
    /**
     * <code>required int32 adverId = 4;</code>
     *
     * <pre>
     *广告主id
     * </pre>
     */
    public boolean hasAdverId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 adverId = 4;</code>
     *
     * <pre>
     *广告主id
     * </pre>
     */
    public int getAdverId() {
      return adverId_;
    }

    private void initFields() {
      zid_ = "";
      pids_ = java.util.Collections.emptyList();
      timestamp_ = 0L;
      adverId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasZid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAdverId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPidsCount(); i++) {
        if (!getPids(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getZidBytes());
      }
      for (int i = 0; i < pids_.size(); i++) {
        output.writeMessage(2, pids_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(3, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, adverId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getZidBytes());
      }
      for (int i = 0; i < pids_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, pids_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, adverId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zamplus.protobuf.uclog.IdsLog.PlatformIds parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zamplus.protobuf.uclog.IdsLog.PlatformIds parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zamplus.protobuf.uclog.IdsLog.PlatformIds parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zamplus.protobuf.uclog.IdsLog.PlatformIds parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zamplus.protobuf.uclog.IdsLog.PlatformIds parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zamplus.protobuf.uclog.IdsLog.PlatformIds parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zamplus.protobuf.uclog.IdsLog.PlatformIds parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zamplus.protobuf.uclog.IdsLog.PlatformIds parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zamplus.protobuf.uclog.IdsLog.PlatformIds parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zamplus.protobuf.uclog.IdsLog.PlatformIds parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zamplus.protobuf.uclog.IdsLog.PlatformIds prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlatformIds}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zamplus.protobuf.uclog.IdsLog.PlatformIdsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_PlatformIds_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_PlatformIds_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    com.zamplus.protobuf.uclog.IdsLog.PlatformIds.class, com.zamplus.protobuf.uclog.IdsLog.PlatformIds.Builder.class);
      }

      // Construct using com.zamplus.protobuf.uclog.IdsLog.PlatformIds.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPidsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        zid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (pidsBuilder_ == null) {
          pids_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          pidsBuilder_.clear();
        }
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        adverId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_PlatformIds_descriptor;
      }

      public com.zamplus.protobuf.uclog.IdsLog.PlatformIds getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      public com.zamplus.protobuf.uclog.IdsLog.PlatformIds build() {
        com.zamplus.protobuf.uclog.IdsLog.PlatformIds result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zamplus.protobuf.uclog.IdsLog.PlatformIds buildPartial() {
        com.zamplus.protobuf.uclog.IdsLog.PlatformIds result = new com.zamplus.protobuf.uclog.IdsLog.PlatformIds(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.zid_ = zid_;
        if (pidsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            pids_ = java.util.Collections.unmodifiableList(pids_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.pids_ = pids_;
        } else {
          result.pids_ = pidsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.adverId_ = adverId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zamplus.protobuf.uclog.IdsLog.PlatformIds) {
          return mergeFrom((com.zamplus.protobuf.uclog.IdsLog.PlatformIds)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zamplus.protobuf.uclog.IdsLog.PlatformIds other) {
        if (other == getDefaultInstance()) return this;
        if (other.hasZid()) {
          bitField0_ |= 0x00000001;
          zid_ = other.zid_;
          onChanged();
        }
        if (pidsBuilder_ == null) {
          if (!other.pids_.isEmpty()) {
            if (pids_.isEmpty()) {
              pids_ = other.pids_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePidsIsMutable();
              pids_.addAll(other.pids_);
            }
            onChanged();
          }
        } else {
          if (!other.pids_.isEmpty()) {
            if (pidsBuilder_.isEmpty()) {
              pidsBuilder_.dispose();
              pidsBuilder_ = null;
              pids_ = other.pids_;
              bitField0_ = (bitField0_ & ~0x00000002);
              pidsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPidsFieldBuilder() : null;
            } else {
              pidsBuilder_.addAllMessages(other.pids_);
            }
          }
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasAdverId()) {
          setAdverId(other.getAdverId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasZid()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasAdverId()) {
          
          return false;
        }
        for (int i = 0; i < getPidsCount(); i++) {
          if (!getPids(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zamplus.protobuf.uclog.IdsLog.PlatformIds parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zamplus.protobuf.uclog.IdsLog.PlatformIds) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string zid = 1;
      private java.lang.Object zid_ = "";
      /**
       * <code>required string zid = 1;</code>
       *
       * <pre>
       *zid
       * </pre>
       */
      public boolean hasZid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string zid = 1;</code>
       *
       * <pre>
       *zid
       * </pre>
       */
      public java.lang.String getZid() {
        java.lang.Object ref = zid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          zid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string zid = 1;</code>
       *
       * <pre>
       *zid
       * </pre>
       */
      public com.google.protobuf.ByteString
          getZidBytes() {
        java.lang.Object ref = zid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          zid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string zid = 1;</code>
       *
       * <pre>
       *zid
       * </pre>
       */
      public Builder setZid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        zid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string zid = 1;</code>
       *
       * <pre>
       *zid
       * </pre>
       */
      public Builder clearZid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        zid_ = getDefaultInstance().getZid();
        onChanged();
        return this;
      }
      /**
       * <code>required string zid = 1;</code>
       *
       * <pre>
       *zid
       * </pre>
       */
      public Builder setZidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        zid_ = value;
        onChanged();
        return this;
      }

      // repeated .Pid pids = 2;
      private java.util.List<com.zamplus.protobuf.uclog.IdsLog.Pid> pids_ =
        java.util.Collections.emptyList();
      private void ensurePidsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          pids_ = new java.util.ArrayList<com.zamplus.protobuf.uclog.IdsLog.Pid>(pids_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.zamplus.protobuf.uclog.IdsLog.Pid, com.zamplus.protobuf.uclog.IdsLog.Pid.Builder, com.zamplus.protobuf.uclog.IdsLog.PidOrBuilder> pidsBuilder_;

      /**
       * <code>repeated .Pid pids = 2;</code>
       *
       * <pre>
       *各平台id列表
       * </pre>
       */
      public java.util.List<com.zamplus.protobuf.uclog.IdsLog.Pid> getPidsList() {
        if (pidsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pids_);
        } else {
          return pidsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Pid pids = 2;</code>
       *
       * <pre>
       *各平台id列表
       * </pre>
       */
      public int getPidsCount() {
        if (pidsBuilder_ == null) {
          return pids_.size();
        } else {
          return pidsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Pid pids = 2;</code>
       *
       * <pre>
       *各平台id列表
       * </pre>
       */
      public com.zamplus.protobuf.uclog.IdsLog.Pid getPids(int index) {
        if (pidsBuilder_ == null) {
          return pids_.get(index);
        } else {
          return pidsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Pid pids = 2;</code>
       *
       * <pre>
       *各平台id列表
       * </pre>
       */
      public Builder setPids(
          int index, com.zamplus.protobuf.uclog.IdsLog.Pid value) {
        if (pidsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePidsIsMutable();
          pids_.set(index, value);
          onChanged();
        } else {
          pidsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Pid pids = 2;</code>
       *
       * <pre>
       *各平台id列表
       * </pre>
       */
      public Builder setPids(
          int index, com.zamplus.protobuf.uclog.IdsLog.Pid.Builder builderForValue) {
        if (pidsBuilder_ == null) {
          ensurePidsIsMutable();
          pids_.set(index, builderForValue.build());
          onChanged();
        } else {
          pidsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Pid pids = 2;</code>
       *
       * <pre>
       *各平台id列表
       * </pre>
       */
      public Builder addPids(com.zamplus.protobuf.uclog.IdsLog.Pid value) {
        if (pidsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePidsIsMutable();
          pids_.add(value);
          onChanged();
        } else {
          pidsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Pid pids = 2;</code>
       *
       * <pre>
       *各平台id列表
       * </pre>
       */
      public Builder addPids(
          int index, com.zamplus.protobuf.uclog.IdsLog.Pid value) {
        if (pidsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePidsIsMutable();
          pids_.add(index, value);
          onChanged();
        } else {
          pidsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Pid pids = 2;</code>
       *
       * <pre>
       *各平台id列表
       * </pre>
       */
      public Builder addPids(
          com.zamplus.protobuf.uclog.IdsLog.Pid.Builder builderForValue) {
        if (pidsBuilder_ == null) {
          ensurePidsIsMutable();
          pids_.add(builderForValue.build());
          onChanged();
        } else {
          pidsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Pid pids = 2;</code>
       *
       * <pre>
       *各平台id列表
       * </pre>
       */
      public Builder addPids(
          int index, com.zamplus.protobuf.uclog.IdsLog.Pid.Builder builderForValue) {
        if (pidsBuilder_ == null) {
          ensurePidsIsMutable();
          pids_.add(index, builderForValue.build());
          onChanged();
        } else {
          pidsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Pid pids = 2;</code>
       *
       * <pre>
       *各平台id列表
       * </pre>
       */
      public Builder addAllPids(
          java.lang.Iterable<? extends com.zamplus.protobuf.uclog.IdsLog.Pid> values) {
        if (pidsBuilder_ == null) {
          ensurePidsIsMutable();
          super.addAll(values, pids_);
          onChanged();
        } else {
          pidsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Pid pids = 2;</code>
       *
       * <pre>
       *各平台id列表
       * </pre>
       */
      public Builder clearPids() {
        if (pidsBuilder_ == null) {
          pids_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          pidsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Pid pids = 2;</code>
       *
       * <pre>
       *各平台id列表
       * </pre>
       */
      public Builder removePids(int index) {
        if (pidsBuilder_ == null) {
          ensurePidsIsMutable();
          pids_.remove(index);
          onChanged();
        } else {
          pidsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Pid pids = 2;</code>
       *
       * <pre>
       *各平台id列表
       * </pre>
       */
      public com.zamplus.protobuf.uclog.IdsLog.Pid.Builder getPidsBuilder(
          int index) {
        return getPidsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Pid pids = 2;</code>
       *
       * <pre>
       *各平台id列表
       * </pre>
       */
      public com.zamplus.protobuf.uclog.IdsLog.PidOrBuilder getPidsOrBuilder(
          int index) {
        if (pidsBuilder_ == null) {
          return pids_.get(index);  } else {
          return pidsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Pid pids = 2;</code>
       *
       * <pre>
       *各平台id列表
       * </pre>
       */
      public java.util.List<? extends com.zamplus.protobuf.uclog.IdsLog.PidOrBuilder> 
           getPidsOrBuilderList() {
        if (pidsBuilder_ != null) {
          return pidsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pids_);
        }
      }
      /**
       * <code>repeated .Pid pids = 2;</code>
       *
       * <pre>
       *各平台id列表
       * </pre>
       */
      public com.zamplus.protobuf.uclog.IdsLog.Pid.Builder addPidsBuilder() {
        return getPidsFieldBuilder().addBuilder(
            com.zamplus.protobuf.uclog.IdsLog.Pid.getDefaultInstance());
      }
      /**
       * <code>repeated .Pid pids = 2;</code>
       *
       * <pre>
       *各平台id列表
       * </pre>
       */
      public com.zamplus.protobuf.uclog.IdsLog.Pid.Builder addPidsBuilder(
          int index) {
        return getPidsFieldBuilder().addBuilder(
            index, com.zamplus.protobuf.uclog.IdsLog.Pid.getDefaultInstance());
      }
      /**
       * <code>repeated .Pid pids = 2;</code>
       *
       * <pre>
       *各平台id列表
       * </pre>
       */
      public java.util.List<com.zamplus.protobuf.uclog.IdsLog.Pid.Builder> 
           getPidsBuilderList() {
        return getPidsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.zamplus.protobuf.uclog.IdsLog.Pid, com.zamplus.protobuf.uclog.IdsLog.Pid.Builder, com.zamplus.protobuf.uclog.IdsLog.PidOrBuilder> 
          getPidsFieldBuilder() {
        if (pidsBuilder_ == null) {
          pidsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.zamplus.protobuf.uclog.IdsLog.Pid, com.zamplus.protobuf.uclog.IdsLog.Pid.Builder, com.zamplus.protobuf.uclog.IdsLog.PidOrBuilder>(
                  pids_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          pids_ = null;
        }
        return pidsBuilder_;
      }

      // required int64 timestamp = 3;
      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 3;</code>
       *
       * <pre>
       *tracking记录的用户访问时间戳
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       *
       * <pre>
       *tracking记录的用户访问时间戳
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       *
       * <pre>
       *tracking记录的用户访问时间戳
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       *
       * <pre>
       *tracking记录的用户访问时间戳
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // required int32 adverId = 4;
      private int adverId_ ;
      /**
       * <code>required int32 adverId = 4;</code>
       *
       * <pre>
       *广告主id
       * </pre>
       */
      public boolean hasAdverId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 adverId = 4;</code>
       *
       * <pre>
       *广告主id
       * </pre>
       */
      public int getAdverId() {
        return adverId_;
      }
      /**
       * <code>required int32 adverId = 4;</code>
       *
       * <pre>
       *广告主id
       * </pre>
       */
      public Builder setAdverId(int value) {
        bitField0_ |= 0x00000008;
        adverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 adverId = 4;</code>
       *
       * <pre>
       *广告主id
       * </pre>
       */
      public Builder clearAdverId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        adverId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PlatformIds)
    }

    static {
      defaultInstance = new PlatformIds(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PlatformIds)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Pid_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Pid_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PlatformIds_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlatformIds_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014IdsLog.proto\"#\n\003Pid\022\020\n\010venderId\030\001 \002(\005\022" +
      "\n\n\002id\030\002 \002(\t\"R\n\013PlatformIds\022\013\n\003zid\030\001 \002(\t\022" +
      "\022\n\004pids\030\002 \003(\0132\004.Pid\022\021\n\ttimestamp\030\003 \002(\003\022\017" +
      "\n\007adverId\030\004 \002(\005B\034\n\032com.zamplus.protobuf." +
      "uclog"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Pid_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Pid_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Pid_descriptor,
              new java.lang.String[] { "VenderId", "Id", });
          internal_static_PlatformIds_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_PlatformIds_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PlatformIds_descriptor,
              new java.lang.String[] { "Zid", "Pids", "Timestamp", "AdverId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
